-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Máy chủ: localhost:3306
-- Thời gian đã tạo: Th10 23, 2022 lúc 04:48 PM
-- Phiên bản máy phục vụ: 10.4.25-MariaDB
-- Phiên bản PHP: 7.4.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Cơ sở dữ liệu: `final`
--

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `account`
--

CREATE TABLE `account` (
  `id` int(11) NOT NULL,
  `username` varchar(64) COLLATE utf8_unicode_ci NOT NULL,
  `password` varchar(64) COLLATE utf8_unicode_ci NOT NULL,
  `name` varchar(64) COLLATE utf8_unicode_ci NOT NULL,
  `email` varchar(64) COLLATE utf8_unicode_ci NOT NULL,
  `role` varchar(64) COLLATE utf8_unicode_ci NOT NULL,
  `age` int(11) DEFAULT NULL,
  `gender` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
  `favoriteSong` varchar(1000) COLLATE utf8_unicode_ci DEFAULT NULL,
  `recentlyListen` varchar(1000) COLLATE utf8_unicode_ci DEFAULT NULL,
  `playlist` varchar(1000) COLLATE utf8_unicode_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Đang đổ dữ liệu cho bảng `account`
--

INSERT INTO `account` (`id`, `username`, `password`, `name`, `email`, `role`, `age`, `gender`, `favoriteSong`, `recentlyListen`, `playlist`) VALUES
(1, 'admin', '$2y$10$UA6d8dqFhh5T1WWWNZGeDetmVrMw8rGwndxxQijdKfBdte8z4l9wm', 'Anh Tiến', 'phamhuynhanhtien123@gmail.com', 'admin', 0, '', '', '', ''),
(2, 'tien123', '$2y$10$9HESZRs.VHOe5TOMGewjUO3NQTispBNBSwbZbpScMLQXc7GgSHhra', '', 'phamhuynhanhtien.12a20.2019@gmail.com', 'user', 0, '', '', '', ''),
(3, 'baokien', '$2y$10$9HESZRs.XpUMfFuTdfssdfdfV15/EybET1B/la5AMnReniaZg.7T8.', '', 'baokien2000@gmail.com', 'user', 0, '', '', '', ''),
(4, 'user1', '$2y$10$1HESZRs.XpUMfF5sghgfhgTsxMGe/EybET1B/la5AMdfReniaZg.7T8.', '', 'user1@gmail.com', 'user', 0, '', '', '', ''),
(5, 'user2', '$2y$10$2HESZRs.XpdF5TrtysdhhdOdsfMGe/EybET1B/la5AMnReniaZg.7T8.', '', 'user2@gmail.com', 'user', 0, '', '', '', ''),
(6, 'user3', '$2y$10$3HESZRs.XpUMddfFrGehjghjsdfss/EybET1B/la5AMnReniaZg.7T8.', '', 'user3@gmail.com', 'user', 0, '', '', '', ''),
(7, 'user4', '$2y$10$4HESZRs.XpUMfF5sdgsdgsdgsdhGe/EybET1B/la5AMnReniaZg.7T8.', '', 'user4@gmail.com', 'user', 0, '', '', '', ''),
(8, 'user5', '$2y$10$5HESZRs.XpUs5TOMGe/EygfhfghagsffbET1B/la5AMnReniaZg.7T8.', '', 'user5@gmail.com', 'user', 0, '', '', '', ''),
(9, 'user6', '$2y$10$6HESZRs.XpUasdfTOMGe/EybEfghhassfsaaT1B/lafnReniaZg.7T8.', '', 'user6@gmail.com', 'user', 0, '', '', '', ''),
(10, 'user7', '$2y$10$7HESZRs.XpUghfghfgfsdf5TOMGe/EybET1B/la5AMfReniaZg.7T8.', '', 'user7@gmail.com', 'user', 0, '', '', '', ''),
(11, 'user8', '$2y$10$8HESZRs.XpUMfF5TOMGe/EybET1B/lasdfdsffs5AMnReniaZg.7T8.', '', 'user8@gmail.com', 'user', 0, '', '', '', ''),
(12, 'user9', '$2y$10$11HESZRs.XpUMgfhgfghfF5TOMGe/EybET1B/la5AMnReniaZg.7T8.', '', 'user9@gmail.com', 'user', 0, '', '', '', ''),
(13, 'user10', '$2y$10$12HESZRs.XpUMfF5TOdfgdfgMGe/EybET1B/la5AMnReniaZg.7T8.', '', 'user10@gmail.com', 'user', 0, '', '', '', '');

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `categories`
--

CREATE TABLE `categories` (
  `id` int(11) NOT NULL,
  `name` varchar(40) COLLATE utf8_unicode_ci NOT NULL,
  `topic` varchar(40) COLLATE utf8_unicode_ci NOT NULL,
  `follow` int(11) NOT NULL,
  `image` varchar(150) COLLATE utf8_unicode_ci NOT NULL,
  `date` datetime NOT NULL,
  `description` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `singers` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `songs` varchar(5000) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Đang đổ dữ liệu cho bảng `categories`
--

INSERT INTO `categories` (`id`, `name`, `topic`, `follow`, `image`, `date`, `description`, `singers`, `songs`) VALUES
(1, 'Nhạc cho thứ 3', 'Lựa chọn hôm nay', 0, 'T3.jpg', '2022-11-16 12:58:41', 'Thứ ba đầy cảm xúc với những Ballad Việt', 'Tăng Duy Tân, Hoàng Thùy Linh, Trịnh Thăng Bình', 'Xin Má Rước Dâu (EDM Version)\nThe Spectre\nNevada'),
(2, 'Indie Buồn', 'Lựa chọn hôm nay', 0, 'IndieBuon.jpg', '2022-11-16 12:58:41', 'Thanh âm Indie buồn', 'Nhật Kim Anh, Trúc Nhân, Ngô Kiến Huy', 'Xin Má Rước Dâu (EDM Version),The Spectre,Một Bước Yêu Vạn Dặm Đau (Piano Cover)'),
(3, 'Heart-break Pop', 'Lựa chọn hôm nay', 0, 'heartbreakPop.jpg', '2022-11-16 12:58:41', 'Heart-break Pop buồn sâu lắng', 'Tăng Duy Tân, Hoàng Thùy Linh, Trịnh Thăng Bình', 'Thuyền Quyên,Nevada,Một Bước Yêu Vạn Dặm Đau (Piano Cover)'),
(4, 'V-Pop Hit ', 'Lựa chọn hôm nay', 0, 'VPopHit.jpg', '2022-11-16 12:58:41', 'V-Pop Những Bản Hit Chậm Mà Chắc', 'Tăng Duy Tân, Hoàng Thùy Linh, Trịnh Thăng Bình', 'Thuyền Quyên,The Spectre,Nevada'),
(5, 'Trending', 'Lựa chọn hôm nay', 0, 'trending.jpg', '2022-11-16 12:58:41', 'Nhạc Trending thịnh hành với giới trẻ', 'Tăng Duy Tân, Hoàng Thùy Linh, Trịnh Thăng Bình', 'Xin Má Rước Dâu (EDM Version),Tấm Lòng Son,Nevada'),
(6, 'TOP 100 Bài Nhạc...', 'Top100', 0, 'top100_NhacTre.jpg', '2022-11-16 12:58:41', 'Top 100 nhạc trẻ', 'Khang Việt, Jack-97, Miu Lê', 'Xin Má Rước Dâu (EDM Version),Tấm Lòng Son,Một Bước Yêu Vạn Dặm Đau (Piano Cover)'),
(7, 'Top 100 Âu Mỹ...', 'Top100', 0, 'top100_AuMy.jpg', '2022-11-16 12:58:41', 'Top 100 Pop Âu Mỹ', 'Khang Việt, Jack-97, Miu Lê', 'Xin Má Rước Dâu (EDM Version),Tấm Lòng Son,Một Bước Yêu Vạn Dặm Đau (Piano Cover)'),
(8, 'Top 100 nhạc...', 'Top100', 0, 'top100_EDM.jpg', '2022-11-16 12:58:41', 'Top 100 EDM', 'Khang Việt, Jack-97, Miu Lê', 'Tấm Lòng Son,Nevada,Một Bước Yêu Vạn Dặm Đau (Piano Cover)'),
(9, 'Top 100 Nhạc Trữ Tình...', 'Top100', 0, 'top100_TruTinh.jpg', '2022-11-16 12:58:41', 'Top 100 Nhạc Trữ Tình', 'Khang Việt, Jack-97, Miu Lê', 'Xin Má Rước Dâu (EDM Version),Thuyền Quyên,Nevada'),
(10, 'Top 100 Nhạc Hàn...', 'Top100', 0, 'top100_Han.jpg', '2022-11-16 12:58:41', 'Top 100 Hàn Quốc', 'Khang Việt, Jack-97, Miu Lê', 'The Spectre,Nevada,Một Bước Yêu Vạn Dặm Đau (Piano Cover)'),
(11, 'V-Pop Tháng 8/2022', 'Nhạc mới mỗi ngày', 0, 'vpop_T8.jpg', '2022-11-16 12:58:41', 'Nhạc hot V-Pop tháng 8 với nhiều ca sĩ khác nhau', 'OnlyC, Phương Ly, Hoàng Thùy Linh', 'Xin Má Rước Dâu (EDM Version),Nevada,Một Bước Yêu Vạn Dặm Đau (Piano Cover)'),
(12, 'US-UK Tháng 8/2022', 'Nhạc mới mỗi ngày', 0, 'usuk_T8.jpg', '2022-11-16 12:58:41', 'Nhạc hot US-UK tháng 8 với nhiều ca sĩ khác nhau', 'Beyoncé, Calvin Harris, Billie Eilish', 'Thuyền Quyên,Tấm Lòng Son,Một Bước Yêu Vạn Dặm Đau (Piano Cover)'),
(13, 'K-Pop Tháng 8/2022', 'Nhạc mới mỗi ngày', 0, 'kpop_T8.jpg', '2022-11-16 12:58:41', 'Nhạc hot K-Pop tháng 8 với nhiều ca sĩ khác nhau', 'ATEEZ, SNSD, STAYC, ITZY', 'Xin Má Rước Dâu (EDM Version),The Spectre,Nevada'),
(14, 'C-Pop Tháng 8/2022', 'Nhạc mới mỗi ngày', 0, 'cpop_T8.jpg', '2022-11-16 12:58:41', 'Nhạc hot C-Pop tháng 8 với nhiều ca sĩ khác nhau', 'Thái Từ Khôn, INTO1, Phó Mộng Đồng', 'Thuyền Quyên,The Spectre,Nevada'),
(15, 'Indie Việt Tháng 8/2022', 'Nhạc mới mỗi ngày', 0, 'indieViet_T8.jpg', '2022-11-16 12:58:41', 'Nhạc hot Indie tháng 8 với nhiều ca sĩ khác nhau', 'Trang, T.R.I, buitruonglinh', 'Tấm Lòng Son,The Spectre,Một Bước Yêu Vạn Dặm Đau (Piano Cover)'),
(23, 'Test', 'Top100', 0, 'shopping.png', '2022-10-23 17:53:16', '2', '2', '2');

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `categorys`
--

CREATE TABLE `categorys` (
  `id` int(11) NOT NULL,
  `name` varchar(40) COLLATE utf8_unicode_ci NOT NULL,
  `numberOfsong` int(11) NOT NULL,
  `follow` int(11) NOT NULL,
  `date` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Đang đổ dữ liệu cho bảng `categorys`
--

INSERT INTO `categorys` (`id`, `name`, `numberOfsong`, `follow`, `date`) VALUES
(4, 'Trữ tình & bolero', 39, 0, '2022-11-16 12:58:41'),
(5, 'EDM', 1, 0, '2022-11-16 12:58:41'),
(6, 'Hip-hop', 1, 0, '2022-11-16 12:58:41'),
(7, 'R&B', 0, 0, '2022-11-16 12:58:41'),
(8, 'Nhạc thiếu nhi', 0, 0, '2022-11-16 12:58:41'),
(9, 'Piano', 0, 0, '2022-11-16 12:58:41'),
(10, 'Rock', 0, 0, '2022-11-16 12:58:41'),
(11, 'Acoustic', 0, 0, '2022-11-16 12:58:41'),
(12, 'Nhạc phim', 0, 0, '2022-11-16 12:58:41'),
(17, 'Remix', 0, 0, '2022-10-23 16:05:04'),
(22, 'Nhạc Không Lời', 0, 0, '2022-10-23 16:10:46'),
(23, 'Indie', 0, 0, '2022-10-23 16:12:46'),
(24, 'Nhạc Trịnh', 0, 0, '2022-10-23 16:12:52'),
(25, 'Guitar', 0, 0, '2022-10-23 16:12:56'),
(26, 'Nhạc Cổ Điển', 0, 0, '2022-10-23 16:13:01'),
(27, 'Latin', 0, 0, '2022-10-23 16:13:06'),
(28, 'Jazz', 0, 0, '2022-10-23 16:13:16'),
(29, 'C-pop', 0, 0, '2022-10-23 16:19:58'),
(30, 'K-pop', 0, 0, '2022-10-23 16:20:08'),
(31, 'US-UK', 0, 0, '2022-10-23 16:20:30'),
(32, 'V-pop', 0, 0, '2022-10-23 16:20:43');

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `reset_token`
--

CREATE TABLE `reset_token` (
  `email` varchar(64) COLLATE utf8_unicode_ci NOT NULL,
  `token` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `expire_on` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Đang đổ dữ liệu cho bảng `reset_token`
--

INSERT INTO `reset_token` (`email`, `token`, `expire_on`) VALUES
('baokien2000@gmail.com', 'd552174233e38556b833745149882451', 1668850766);

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `songs`
--

CREATE TABLE `songs` (
  `id` int(11) NOT NULL,
  `name` varchar(40) COLLATE utf8_unicode_ci NOT NULL,
  `singer` varchar(40) COLLATE utf8_unicode_ci NOT NULL,
  `date` datetime NOT NULL,
  `category` varchar(40) COLLATE utf8_unicode_ci NOT NULL,
  `nation` varchar(40) COLLATE utf8_unicode_ci NOT NULL,
  `lyric` varchar(3000) COLLATE utf8_unicode_ci DEFAULT NULL,
  `listens` int(11) NOT NULL,
  `comments` int(11) NOT NULL,
  `downloads` int(11) NOT NULL,
  `file` varchar(100) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Đang đổ dữ liệu cho bảng `songs`
--

INSERT INTO `songs` (`id`, `name`, `singer`, `date`, `category`, `nation`, `lyric`, `listens`, `comments`, `downloads`, `file`) VALUES
(1, 'Xin Má Rước Dâu (EDM Version)', 'Diệu Kiên', '2022-11-16 12:58:41', 'Nhạc Trẻ', 'Việt Nam', 'Anh ra mà xem nay làng bên rộn tiếng cười vui\nChú rể cô dâu đang cùng nâng chén rượu giao bôi\nVậy mà sao chưa thấy đâu bao mùa trăng không thấy cau trầu\nEm mong chờ câu anh hứa mai này qua đón em mần dâu\nRồi từng đêm lén nhìn nhau trao vài câu hỏi han ấm nồng\nChẳng cần nhung gấm giàu sang thiếu gì đâu nơi anh tấm lòng\nĐồng bằng sông nước mình nay đâu có thua xa gì phố đô thành?\nCoi mà như có thương thì anh phải lo tính sao cho đành\nAnh ơi nắng mưa dãi dầu về nhà xin má rước con dâu\nEm thương với ưng mình anh thôi cho tới khi ta bạc mái đầu\nMong sao tấm thân sẽ trao về người trân quý, trái tim em son vàng\nNắm lấy níu tay dắt em dù qua mấy sông hay đèo núi cao\nRồi từng đêm lén nhìn nhau trao vài câu hỏi han ấm nồng\nChẳng cần nhung gấm giàu sang thiếu gì đâu nơi anh tấm lòng\nĐồng bằng sông nước mình nay đâu có thua xa gì phố đô thành?\nCoi mà như có thương thì anh phải lo tính sao cho đành\nAnh ơi nắng mưa dãi dầu về nhà xin má rước con dâu\nEm thương với ưng mình anh thôi cho tới khi ta bạc mái đầu\nMong sao tấm thân sẽ trao về người trân quý, trái tim em son vàng\nNắm lấy níu tay dắt em dù qua mấy sông hay đèo núi cao\nAnh ơi nắng mưa dãi dầu về nhà xin má rước con dâu\nEm thương với ưng mình anh thôi cho đến khi ta bạc mái đầu\nMong sao tấm thân sẽ trao về người trân quý, trái tim em son vàng\nNắm lấy níu tay dắt em dù qua mấy sông hay đèo núi cao\nBông xanh, bông trắng rồi lại vàng bông ơ rượng ơ\nThương anh em chờ em đợi ơ rượng ơ\nChờ anh rước em về nhà\nCho thỏa lòng nhớ mong\nChờ anh rước em về nhà\nĐôi mình xây ước mơ', 0, 0, 0, 'xinmaruocdauedm.mp3'),
(2, 'Thuyền Quyên', 'Diệu Kiên', '2022-11-16 12:58:42', 'Nhạc Trẻ', 'Việt Nam', 'Xa xa bóng người thương\nThấp thoáng trước thềm nhà đang đưa dâu...\nNơi đây, phấn son áo màu\nEm sắp theo chồng bỏ lại bến sông kia chờ mong...\nKhải lên khúc nhạc hoàng cầm buồn ngày mình biệt ly\nCung oán, cung sầu nặng lòng tiễn chân người ra đi\nXác pháo vu quy bên thềm\nCó chăng hạnh phúc êm đềm?\nĐời người con gái đục trong\nMười hai bến nước long đong...\nDặm ngàn thiên lí tiễn người đi\nMây nước u buồn ngày biệt ly\nKhóc cho duyên mình\nĐoạn trường thương loan đò sang ngang\nÁo mới em cài màu hoa cưới\nSánh bước bên người cùng duyên mới\nNâng chén tiêu sầu\nKhải một cung đàn từ biệt nhau...\nYêu nhau, cởi áo cho nhau\nVề nhà mẹ hỏi qua cầu gió bay\nTừ nay hết duyên em trả áo\nXem như hết tình mình đã trao\nPhận duyên ta lỡ, cung thương đứt đoạn, sầu đối gương loan\nDặm ngàn thiên lý tiễn người đi\nMây nước u buồn ngày biệt ly\nKhóc cho duyên mình\nĐoạn trường thương loan đò sang ngang\nÁo mới em cài màu hoa cưới\nSánh bước bên người cùng duyên mới\nNâng chén tiêu sầu\nKhải một cung đàn từ biệt nhau\nDặm ngàn thiên lý tiễn người đi\nMây nước u buồn ngày biệt ly\nKhóc cho duyên mình\nĐoạn trường thương loan đò sang ngang\nÁo mới em cài màu hoa cưới\nSánh bước bên người cùng duyên mới\nNâng chén tiêu sầu\nKhải một cung đàn từ biệt nhau\nBướm lượn là bướm ối ả nó bay...\nBướm dậu là bướm ối ả nó bay...\nCá lặn là cá ối ả nó bơi...\nCá lội là cá ối ả nó bơi...', 0, 0, 0, 'thuyenquyen.mp3'),
(3, 'Tấm Lòng Son', 'H-Kray', '2022-11-16 12:58:43', 'Nhạc Trẻ', 'Việt Nam', 'Ver:\nThương cho tấm thân cơ hàn, ngậm ngùi lặng nhìn con đò sang ngang\nMộng vàng nay hoá tro tàn khi trên xe hoa ai đón đưa nàng\nNhân duyên từ nay đứt đoạn, để lại một mình thân này héo hon\nCuộc tình năm xưa chẳng còn, nhưng sao mãi giữ một tấm lòng son.\n\nPre-Chorus:\nHà cờ chi để ta phải xa cách rời, thiên ý trêu ngươi cho ta phận duyên đôi lứa đôi nơi\nLời hẹn hứa xưa giờ đây cũng sẽ hoá thừa\nMơ ước bên nhau đành thôi gửi trao người sau đón đưa\n\nChorus:\nGiọt buồn vương trên màu mắt ai\nPhía xa xăm có tiếng thở dài\nKhắc sâu mối tình không phôi phai\nTiếc cho duyên phận mình ngang trái\nTừng chiều cô liêu buồn hắt hiu\nLẽ loi chỉ tôi với cánh diều\nTháng năm cứ ngày chờ đêm trông\nNhưng sao chẳng chút hy vọng\nThuyền giờ sang sông bỏ lại bến xưa\nTiếng ai đang nấc sau ô cửa\nThả trôi nổi niềm trong cơn mưa\nCánh hoa xưa giờ còn đâu nữa\nHẹn lại lương duyên ở kiếp sau\nSẽ tay nắm tay đến khi bạc đầu\nDẫu cho có ngàn vạn thương đau\nCũng không để mất nhau\n\nRap:\nBến đò này đợi ngóng trông, đón đưa em đi theo chồng\nAnh không thể phủ lòng này, một lòng nhỏ nhoi không đổi thay\nSầu này ta nên biết, không để lạc mất nhau\nVơi sầu với tấm bi hài như ánh lửa vàng đốt tro thiên thai\nKiếp này không thân, cũng không duyên, cũng không phận\nVu quy ngày đó hạnh phúc chúc em bái đường thành thân\nKhóc làm gì nữa cô ơi em sắp xa vùng làng quê\nBước chân tới thành thị em cùng tình làng nghĩa phu thê\nYêu nhau khổ làm chi, để bây giờ xa cách lại biệt từ\nChỉ biết cuối đầu trách do bản thân khi đọc thấu hiểu dòng tâm thư\nKhông nên gặp cũng đã gặp, không nên thương cũng đã thương\nVì em đã không thương anh nên bây giờ phải xa lánh\n\nMong... ngày đó quay lại đừng xảy ra\nĐừng giữ chặt cô đến tới lúc này hãy để tâm hồn này thoát ra\nBao nhiêu niềm vui bây giờ trở thành niềm tin\nLà vì do thân mình không thấu thật chỉ giấu kín\n\nVer 2\nNơi kia có ngờ nơi đây cứ chờ dẫu cho chẳng trọn vẹn bao nhiêu ý thơ\nMông lung đứt đoạn dây tơ vỡ lở bao giấc mơ\nAi đưa chuyến đò xuôi theo cánh cò đến nơi giàu sang nhung gấm hoa\nRiêng tôi ở lại ôm thương nhớ hoài hình dung chẳng phai\n\nChorus:\nGiọt buồn vương trên màu mắt ai\nPhía xa xăm có tiếng thở dài\nKhắc sâu mối tình không phôi phai\nTiếc cho duyên phận mình ngang trái\nTừng chiều cô liêu buồn hắt hiu\nLẽ loi chỉ tôi với cánh diều', 0, 0, 0, 'tamlongson.mp3'),
(4, 'The Spectre', 'Alan Walker', '2022-11-16 12:58:44', 'Electronic', 'Việt Nam', 'Hello, hello\nCan you hear me\nAs I scream your name?\nHello, hello\nDo you need me\nBefore I fade away?\nIs this a place that I call home?\nTo find what I\'ve become\nWalk along the path unknown\nWe live, we love, we lie\nDeep in the dark, I don\'t need the light\nThere\'s a ghost inside me\nIt all belongs to the other side\nWe live, we love, we lie\n(We live, we love, we lie)\nHello, hello\nNice to meet you\nVoice inside my head\nHello, hello\nI believe you\nHow can I forget?\nIs this a place that I call home?\nTo find what I\'ve become\nWalk along the path unknown\nWe live, we love, we lie\nDeep in the dark, I don\'t need the light\nThere\'s a ghost inside me\nIt all belongs to the other side\nWe live, we love, we lie\n(We live, we love, we lie)\nWe live, we love, we lie', 0, 0, 0, 'Spectre.mp3'),
(5, 'Nevada', 'Vicetone,Cozi Zuehlsdorff', '2022-11-16 12:58:44', 'Hip-hop', 'Việt Nam', 'I\'ve been painting every fence I know\nEvery color bleeds into the same\n\'Cause before you go and walk away\nYeah, you better know where you\'re going\nHey ya, hey ya\nYou\'re a wanderer, just like me\nHey ya, hey ya\nYeah, you better know where you\'re going\nYeah, you better know where you\'re going\nI\'ve been painting every fence I know\nEvery color bleeds into the same\n\'Cause before you go and walk away\nYeah, you better know where you\'re going\nHey ya, hey ya\nYou\'re a wanderer just like me\nHey ya, hey ya\nYeah, you better know where you\'re going\nYeah, you better know where you\'re going\nHey ya, hey ya\nYou\'re a wanderer just like me\nHey ya, hey ya\nYeah, you better know where you\'re going\nYeah, you better know where you\'re going\nYeah, you better know where you\'re going\nYou\'re a wanderer just like me\nYeah, you better know where you\'re going\nYou\'re a wanderer just like me', 0, 0, 0, 'Nevada.mp3'),
(10, 'Em giờ thân gái long đong', 'Minh Luân', '2022-10-23 19:27:32', 'Trữ tình & bolero', 'Việt Nam', 'Em rót đầy ly rượu đắng\nBỏ trinh trắng lại quê nhà\nSay mê trong chốn phồn hoa\nNâng ly em uống từng giọt rượu nồng\nÔm ấp người lạ vào lòng\nEm giờ thân gái long đong\nĐêm xuống dần chân mỏi gối\nNhảy theo tiếng nhạc quay cuồng\nEm đang hoang phí tuổi xuân\nKhuya nay\nTrên bước đường về nghìn trùng\nMưa ướt cuộc đời lạnh lùng\nEm buồn em khóc mình em\nCuộc sống xa hoa\nNhưng lòng em nhớ thương quê nhà\nCơm mắm dưa cà\nThắm tình quê hương thiết tha\nĐời lắm phong ba\nĐâu đẹp như giấc mơ ngày đó\nEm hãy quay về\nCó mẹ già mỏi mắt chờ mong\nSon phấn làm phai mộng ước\nĐời em lắm nổi ưu phiền\nTrôi đi năm tháng hồn nhiên\nThôi em gian dối người để làm gì\nCho héo tàn tuổi dậy thì\nEm về em hãy về đi\nCuộc sống xa hoa\nNhưng lòng em nhớ thương quê nhà\nCơm mắm dưa cà\nThắm tình quê hương thiết tha\nĐời lắm phong ba\nĐâu đẹp như giấc mơ ngày đó\nEm hãy quay về\nCó mẹ già mỏi mắt chờ mong\nSon phấn làm phai mộng ước\nĐời em lắm nổi ưu phiền\nTrôi đi năm tháng hồn nhiên\nThôi em gian dối người để làm gì\nCho héo tàn tuổi dậy thì\nEm về em hãy về đi\nThôi em gian dối người để làm gì\nCho héo tàn tuổi dậy thì\nEm về em hãy hãy về đi', 0, 0, 0, 'Em-Gio-Than-Gai-Long-Dong-Minh-Luan.mp3'),
(21, 'Gõ Cửa', 'Khưu Huy Vũ', '2022-10-23 20:08:40', 'Trữ tình & bolero', 'Việt Nam', 'Nếu có lần em gõ cửa ghé thăm\nGác vắng buồn thiu khung cảnh âm thầm\nEm ơi người xưa đã ra đi\nKhông gặp em lúc phân ly\nKhông cho sầu thương đổ bờ mi\nLuyến ái làm chi sẽ khổ lắm em\nÐếm lá mùa thu vương đổ bên thềm\nKhi sơn hà nhiều nỗi điêu linh\nÐôi bờ đôi ngã phân tranh\nNghĩ chi nhiều đến chuyện chúng mình\nÐêm nay ngoài xa mịt mờ\nNằm đây ôm chiếc ba lô\nThấy đời vương cả ý thơ\nNiềm vui là kiếp sống tung hoành\nLà chiến đấu cho mình\nVà mong mối tình đẹp xinh\nNếu biết rằng tôi đã bỏ cố hương\nKhoác áo đời trai binh lửa lên đường\nTôi tin rằng người ấy thêm thương\nVui lòng cho kẻ phong sương\nDấn thân ngoài súng đạn sa trường\nLuyến ái làm chi sẽ khổ lắm em\nÐếm lá mùa thu vương đổ bên thềm\nKhi sơn hà nhiều nỗi điêu linh\nÐôi bờ đôi ngã phân tranh\nNghĩ chi nhiều đến chuyện chúng mình\nÐêm nay ngoài xa mịt mờ\nNằm đây ôm chiếc ba lô\nThấy đời vương cả ý thơ\nNiềm vui là kiếp sống tung hoành\nLà chiến đấu cho mình\nVà mong mối tình đẹp xinh\nNếu biết rằng tôi đã bỏ cố hương\nKhoác áo đời trai binh lửa lên đường\nTôi tin rằng người ấy thêm thương\nVui lòng cho kẻ phong sương\nDấn thân ngoài súng đạn sa trường\nTôi tin rằng người ấy thêm thương\nVui lòng cho kẻ phong sương\nDấn thân ngoài súng đạn sa trường', 0, 0, 0, 'khuu-huy-vu-nhac-bolero-tru-tinh-nghe-mot-lan-la-me.mp3'),
(22, 'Cô Hàng Xóm', 'Mai Lệ Quyên, Đoàn Minh', '2022-10-23 20:11:13', 'Trữ tình & bolero', 'Việt Nam', 'Vùng ngoại ô, tôi có căn nhà tranh\nTuy bé nhưng thật xinh\nTháng ngày sống riêng một mình\nNhà ở bên em sống trong giàu sang\nQuen gấm nhung đài trang\nĐi về xe đón đưa\nĐêm đêm dưới ánh trăng vàng\nTôi với cây đàn âm thầm thở than\nVà cô nàng bên xóm\nMỗi lúc lên đèn sang nhà làm quen\nTôi ca không hay tôi đàn nghe cũng dở\nNhưng nàng khen nhiều và thật nhiều\nLàm tôi thấy trong tâm tư xôn xao\nNhư lời âu yếm mặn nồng\nCủa đôi lứa yêu nhau\nHai năm trôi qua\nNhưng tình không dám ngỏ\nTôi sợ thân mình là bọt bèo\nLàm sao ước mơ duyên tơ mai sau\nTôi sợ ngang trái\nLàm mộng đời chua xót thương đau\nRồi một hôm tôi quyết đi thật xa\nTôi cố quên người ta\nNhưng hình bóng không xa mờ\nNhờ thời gian phương thuốc hay thần tiên\nChia cách đôi tình duyên\nNên người xưa đã quên\nHôm nay đón cánh thiệp hồng\nEm báo tin mừng lấy chồng giàu sang\nĐời em nhiều may mắn\nCó nhớ anh nhạc sĩ nghèo này không\nTôi ca không hay tôi đàn nghe cũng dở\nNhưng nàng khen nhiều và thật nhiều\nLàm tôi thấy trong tâm tư xôn xao\nNhư lời âu yếm mặn nồng\nCủa đôi lứa yêu nhau\nHai năm trôi qua\nNhưng tình không dám ngỏ\nTôi sợ thân mình là bọt bèo\nLàm sao ước mơ duyên tơ mai sau\nTôi sợ ngang trái\nLàm mộng đời chua xót thương đau\nRồi một hôm tôi quyết đi thật xa\nTôi cố quên người ta\nNhưng hình bóng không xa mờ\nNhờ thời gian phương thuốc hay thần tiên\nChia cách đôi tình duyên\nNên người xưa đã quên\nHôm nay đón cánh thiệp hồng\nEm báo tin mừng lấy chồng giàu sang\nĐời em nhiều may mắn\nCó nhớ anh nhạc sĩ nghèo này không\nĐời em nhiều may mắn\nCó nhớ anh nhạc sĩ nghèo này không', 0, 0, 0, 'mai-le-quyen-and-doan-minh.mp3'),
(23, 'Lau Buồn Bến Mộng', 'Dương Hồng Loan', '2022-10-23 20:15:37', 'Trữ tình & bolero', 'Việt Nam', 'Bao đêm em vẫn mong chờ\nBóng hình anh em vẫn mong chờ\nNgày nao anh nói rằng\nTa sẽ bên nhau\nEm luôn ấp ủ trong lòng\nMãi nuôi ước mộng\nXây thắm tình duyên\nBên sông em đứng thẫn thờ\nCứ chờ mong em đứng thẫn thờ\nHàng lau bến sông buồn\nTheo gió đong đưa\nNhư em trao cả ân tình\nNhớ anh nuốt lệ đêm vắng riêng mình ên\nChờ mộng tình nay đã tan còn đâu\nNgười có hay trái tim em sầu\nAnh quên năm tháng êm đềm\nQuên hết kỷ niệm những lúc buồn vui\nSông đêm trăng buồn em soi\nHoang mang ơi người người hỡi\nTình em thương nhớ\nGiờ người thì cất bước quay mặt đi\nĐành bỏ em xót xa bao ngày\nBiết ai ai hiểu cho tình\nAi sẽ yêu mình nên có còn tin\nThân em lau buồn mênh mông\nĐau thương dâng tràn bến sông\nBuồn cho con nước để trăng rẽ dòng\nBên sông em đứng thẫn thờ\nCứ chờ mong em đứng thẫn thờ\nHàng lau bến sông buồn\nTheo gió đong đưa\nNhư em trao cả ân tình\nNhớ anh nuốt lệ đêm vắng riêng mình ên\nChờ mộng tình nay đã tan còn đâu\nNgười có hay trái tim em sầu\nAnh quên năm tháng êm đềm\nQuên hết kỷ niệm những lúc buồn vui\nSông đêm trăng buồn em soi\nHoang mang ơi người người hỡi\nTình em thương nhớ\nGiờ người thì cất bước quay mặt đi\nĐành bỏ em xót xa bao ngày\nBiết ai ai hiểu cho tình\nAi sẽ yêu mình nên có còn tin\nThân em lau buồn mênh mông\nĐau thương dâng tràn bến sông\nBuồn cho con nước để trăng rẽ dòng\nThân em lau buồn mênh mông\nĐau thương dâng tràn bến sông\nBuồn cho con nước để trăng rẽ dòng', 0, 0, 0, 'LauBuonBenMong-DuongHongLoan-8054045.mp3'),
(24, 'Bằng Lăng Tím Mong Chờ', 'Khưu Huy Vũ, Quỳnh Trang', '2022-10-23 20:22:00', 'Trữ tình & bolero', 'Việt Nam', 'Anh hái nụ hoa xinh\nCài lên mái tóc em dài\nEm hỏi hoa gì\nAnh bảo rằng hoa tím bằng lăng\nRồi lặng nhìn nhau\nMà sao mắt ướt lệ sầu\nVì mai hai đứa ra trường\nHoa tím buồn gợi nhớ thương thêm\nBao tháng ngày bên nhau\nMình chung một lối đi về\nMà nay xa rồi lòng ngậm ngùi\nLưu luyến đầy vơi\nMỗi người một nơi\nCòn đâu những lúc tan trường\nĐường quen hai đứa vui đùa\nQua mấy mùa mình chung nắng mưa\nRồi thời gian trôi\nEm trở về Bến Tre xứ dừa\nCòn anh miền Đông lòng luôn chờ mong\nHai đứa mình chung một dòng sông\nĐừng quên câu biển hẹn non thề\nNắng mai anh sẽ về\nNơi đây quê em miền Tây\nThôi nhé mình xa nhau\nMàu hoa tím mãi mong chờ\nDù ở nơi nào\nThì trong lòng luôn nhớ về nhau\nMùa hè năm sau\nBằng lăng tím nở bên đường\nNgười ơi có nhớ sân trường\nNhớ một người luôn nhớ thương anh\nBao tháng ngày bên nhau\nMình chung một lối đi về\nMà nay xa rồi lòng ngậm ngùi\nLưu luyến đầy vơi\nMỗi người một nơi\nCòn đâu những lúc tan trường\nĐường quen hai đứa vui đùa\nQua mấy mùa mình chung nắng mưa\nRồi thời gian trôi\nEm trở về Bến Tre xứ dừa\nCòn anh miền Đông lòng luôn chờ mong\nHai đứa mình chung một dòng sông\nĐừng quên câu biển hẹn non thề\nNắng mai anh sẽ về\nNơi đây quê em miền Tây\nThôi nhé mình xa nhau\nMàu hoa tím mãi mong chờ\nDù ở nơi nào\nThì trong lòng luôn nhớ về nhau\nMùa hè năm sau\nBằng lăng tím nở bên đường\nNgười ơi có nhớ sân trường\nNhớ một người luôn nhớ thương anh\nMùa hè năm sau\nBằng lăng tím nở bên đường\nNgười ơi có nhớ sân trường\nNhớ một người luôn nhớ thương anh', 0, 0, 0, 'BangLangTimMongCho-KhuuHuyVuQuynhTrang-8033398.mp3'),
(25, 'Cuộc tình đã xa', 'Lâm Vũ', '2022-10-23 20:23:41', 'Trữ tình & bolero', 'Việt Nam', 'Sỏi đá vẫn nhớ, dấu chân người đã qua\nĐường vắng phố cũ, tháng năm nào thiết tha\nEm giờ đây đã xa, nơi phương trời lạnh giá\nÔm nỗi cô đơn buồn bã.\n\nNhịp chân bâng khuâng, gót đã mòn lối đi\nHạnh phúc mãi mãi, vẫn như dòng nước trôi\nCho dù ai cố quên, bao ân tình thuở ấy\nTôi vẫn chờ mong bóng người.\n\nLệ rơi trên xác lá úa, nhạt nhòa ướt mi\nQuạnh hiu đêm tối trống vắng, lạc loài đắng cay\nBuồn thương cho thân tôi bơ vơ, rã rời niềm nhung nhớ.\n\nNgười yêu chôn dấu dĩ vãng, cuộc tình lỡ làng\nTình yêu ơi mãi tiếc nuối, kỷ niệm xưa còn đâu nữa\nKhóc cho vơi ngàn đắng cay, vẫn mong em về chốn đây\nMột mình tôi ôm giá băng theo tháng ngày.', 0, 0, 0, 'Cuoctinhdaxa-LamVu_jst7.mp3'),
(26, 'Tình Xưa', 'Ngọc Hân, Khưu Huy Vũ', '2022-10-23 20:28:48', 'Trữ tình & bolero', 'Việt Nam', 'Giữa Sài Gòn phồn hoa chợt nghe câu hát dân ca\nLòng tôi nhớ một người\nNgọt ngào lời ru thắm đượm tình quê\nNgược thời gian hình bóng xưa quay về\nNgười em gái nhỏ dịu hiền\nCa nhạc buồn \"gợi nhớ quê hương\".\n\n(*) Tiếng đàn cùng lời ca\nNgày xưa hai đứa bên nhau\nTình vẫn sống dạt dào.\nDệt mộng trăng sao\nCó nào ngờ đâu đời hợp tan\n\nDòng nước trôi qua cầu\nGiờ nơi xứ lạ quê người\nAi dạo đàn mỗi lúc em ca?\nKhoảng cách đôi ta ngày xưa\nChỉ một con đường\n\nMà nỗi nhớ ai ơi dài dô tận\nNhư biển xanh có bao giờ hết mặn\nNhư trái tim này em xin tặng riêng anh\nCách biệt ngàn *** xa\nChiều nay nghe khúc dân ca\n\nLòng em có chạnh buồn chuyện tình đôi ta\nGởi trọn bài ca để tình quê\nCòn mãi không phai nhòa\nDòng sông bến cũ câu hò\nPhương trời nào còn nhớ không em?', 0, 0, 0, 'TinhXua-NgocHanKhuuHuyVu-5335036.mp3'),
(27, 'Mờ E Me Nặng Mẹ', 'Hương Lan', '2022-10-23 20:30:51', 'Trữ tình & bolero', 'Việt Nam', 'Thuở bé thơ con bên mẹ yêu\nMẹ hát ru con vào giấc ngủ\nTrưa hè tiếng chim chích kêu\nLíu lo bên hàng tre xanh\nMẹ tôi lặng lẽ dạo quanh\nNhặt lúa rơi trên đồng còn sót\nTrời nắng chang chang thân mẹ không màng\nMong đàn con không dở dang\nVẻ vang trên đường tương lai\nHọc hành chẳng thua một ai\nThằng Tư vào lớp một\nEm sau vừa biết bò\nThương mẹ thân cánh cò\nGian nan sớm chiều lo\nTrời về đêm trở gió\nThương mẹ tôi ốm o\nDạy thằng Tư đọc chữ\nÊ a vào lớp một\nMờ e me nặng mẹ\nCon nay đã biết đọc\nMắt mẹ ngấn lệ mừng\nTương lai mới là đây\nĐời mẹ bao gian khó\nMong rằng con lớn khôn\nTình mẹ như biển lớn\nCho con hết cuộc đời\nRồi khi lớn khôn\nCon ở miền xa\nThèm nghe tiếng ru\nCủa mẹ thuở nào\nThèm được nghe tiếng dạy em\nTối hôm đèn dầu khe khẽ\nMờ e me nặng mẹ\nNhặt lúa rơi trên đồng còn sót\nTrời nắng chang chang thân mẹ không màng\nMong đàn con không dở dang\nVẻ vang trên đường tương lai\nHọc hành chẳng thua một ai\nThằng Tư vào lớp một\nEm sau vừa biết bò\nThương mẹ thân cánh cò\nGian nan sớm chiều lo\nTrời về đêm trở gió\nThương mẹ tôi ốm o\nDạy thằng Tư đọc chữ\nÊ a vào lớp một\nMờ e me nặng mẹ\nCon nay đã biết đọc\nMắt mẹ ngấn lệ mừng\nTương lai mới là đây\nĐời mẹ bao gian khó\nMong rằng con lớn khôn\nTình mẹ như biển lớn\nCho con hết cuộc đời\nRồi khi lớn khôn\nCon ở miền xa\nThèm nghe tiếng ru\nCủa mẹ thuở nào\nThèm được nghe tiếng dạy em\nTối hôm đèn dầu khe khẽ\nMờ e me nặng mẹ\nThèm được nghe tiếng dạy em\nTối hôm đèn dầu khe khẽ\nMờ e me nặng mẹ', 0, 0, 0, 'MoEMeNangMe-HuongLan-7783904.mp3'),
(28, 'Cậu Ba', 'Khưu Huy Vũ, Kim Chi', '2022-10-23 20:32:02', 'Trữ tình & bolero', 'Việt Nam', 'Hò ơi\nBây giờ mận hỏi thiệt đào\nVườn hồng có lối\nAi vào hay chưa\nỦa, ai vậy ta\nThôi kệ, nghe nè\nHò ơi\nMận hỏi thì đào xin thưa\nVườn hồng có lối, nhưng chưa ai vào\nChưa ai vào\nVậy anh vào có được không\nỦa, cậu ba\nCậu ba đi chăm lúa ruộng hả\nNữa, lại cậu ba kêu bằng anh đi\nThôi, lỡ ông bà bá hộ biết\nLà chết em đó\nCó gì đâu, anh thương em thật mà\nAnh con bá hộ\nĐất đai cò bay thẳng cánh\nNhà lắm trâu bò, lúa thóc đầy sân\nCòn em đây con của tá điền\nNhà tranh vách lá\nNào dám nói yêu anh\nBa má anh không tham sang phụ khó\nVật chất kim tiền có chắc bền lâu\nBa má chọn dâu siêng năng giỏi giắn\nHiếu thảo ngoan hiền thùy mị nết na\nMiệng đời dèm pha\nKhông môn đăng hộ đối\nThân em dưới thấp học đòi trèo cao\nSợ lỡ té đau bà con chê cười\nDám đâu đèo bồng lấy chồng giàu sang\nMặc kệ người ta\nThương nhau thì mình cưới\nBa má thuận lòng\nNội ngoại cũng đều ưng\nXứng lứa vừa đôi yêu thương đậm đà\nTrên dưới thuận hòa cần gì xa hoa\nAnh con bá hộ\nBiết bao cô nàng tương xứng\nKết nghĩa châu trần\nCho nở mặt mẹ cha\nCòn em đây thắp kém nghèo hèn\nTay chân dính phèn nào dám mơ cao\nEm đừng có lo\nBa má anh thấy vậy chứ dễ lắm\nHay giúp đỡ và thương người nghèo khó\nGiúp đỡ và thương người\nVới việc chọn dâu\nĐâu có liên quan gì nhau\nVậy chứ chị hai anh lấy chồng nghèo\nMà ba má anh\nCó cấm cản gì đâu\nCô hai lấy chồng xứ xa\nCòn nhà em thuê đất\nLàm đong lúa ruộng cho nhà anh\nCho nên khó lắm\nAnh con bá hộ\nĐất đai cò bay thẳng cánh\nNhà lắm trâu bò, lúa thóc đầy sân\nCòn em đây con của tá điền\nNhà tranh vách lá\nNào dám nói yêu anh\nBa má anh không tham sang phụ khó\nVật chất kim tiền có chắc bền lâu\nBa má chọn dâu siêng năng giỏi giắn\nHiếu thảo ngoan hiền thùy mị nết na\nMiệng đời dèm pha\nKhông môn đăng hộ đối\nThân em dưới thấp học đòi trèo cao\nSợ lỡ té đau bà con chê cười\nDám đâu đèo bồng lấy chồng giàu sang\nMặc kệ người ta\nThương nhau thì mình cưới\nBa má thuận lòng\nNội ngoại cũng đều ưng\nXứng lứa vừa đôi yêu thương đậm đà\nTrên dưới thuận hòa cần gì xa hoa\nAnh con bá hộ\nBiết bao cô nàng tương xứng\nKết nghĩa châu trần\nCho nở mặt mẹ cha\nCòn em đây thắp kém nghèo hèn\nTay chân dính phèn nào dám mơ cao\nCòn em đây thắp kém nghèo hèn\nTay chân dính phèn nào dám mơ cao\nNếu anh thuyết phục được\nBa má đồng ý\nVậy em có bằng lòng\nLàm vợ anh không\nEm, cũng không biết nữa\nHả\nThôi trưa rồi, em về trước đây\nBé năm, bé năm à', 0, 0, 0, 'CauBa-KhuuHuyVuKimChi-7892549.mp3'),
(29, 'Chim Trắng Mồ Côi', 'Đan Trường', '2022-10-23 20:33:41', 'Trữ tình & bolero', 'Việt Nam', 'Tình anh như nước con sông dài\nCon nước về cho cây trái trổ bông\nTình em như lúa xanh trên đồng\nCây lúa chờ ngày mùa đơm bông\nChiều quê hai đứa hai vui đùa\nEm cánh cò anh chim sáo mồ côi\nPhù sa vun đắp chia đôi bờ\nAnh bến bồi em bến lỡ mong chờ\nThương nghe câu mãi đẩy\nNhớ điệu lý tình tan\nNgân nga khúc chờ nhau khi mùa lúa chín sẽ đón đưa nhau\nTrăng sắp tàn trôi xa nơi bến đẩu ,chim sáo bay xa mãi không về\nEm vẫn chờ anh nơi đây bến lỡ ,rồi nhớ thương câu hát mong chờ\nThương chim quyên nức nở ,thương con cá rô trên đồng\nNghe chim trắng mồ côi ,đâu còn ai đón ai nhớ mà mong\nƠ ơ ơ ơ...ơ lý nàng ơiiiiii....(Ơ lý nàng ơi)\nƠ lý nàng ơi em thương mà em đợi, con nước buồn tênh câu hát lý mong chờ\nMùa lúa thơm đã chín chín lâu rồi, mà bấy lâu anh chưa ghé về thăm\nƠ ơ ơ chim sáo mồ côi (chim trắng mình ơi) chim sáo mồ côi thương anh mà em đợi\nĐêm trắng cò than nghe tái tái tê lòng,ngồi nhớ anh em ngó ngó lên trời\nChim sáo không về cánh cò mồ côi, em nhớ anh nhiều sao phụ tình em.......', 0, 0, 0, 'ChimTrangMoCoi-DanTruong_38fsb.mp3'),
(30, 'Người Đã Như Mơ', 'Ngọc Hân', '2022-10-23 20:35:33', 'Trữ tình & bolero', 'Việt Nam', 'Ngày xưa quen nhau\nBên đường vắng hoa nở mau\nNgày nay xa nhau\nHoa vừa khép cánh ban đầu\nNgười ngỡ gặp nhau\nNhư duyên kiếp đưa ta vào\nChiều rơi về đâu\nNgày xưa quen nhau\nEm vừa biết dăm ước mơ\nBờ vai ngây thơ\nÔm làn tóc rối ơ thờ\nTình mới vừa đôi môi\nE ấp câu mong chờ\nNgười đã như mơ\nTiếng hát tiếng cười\nCòn đâu đó trong đêm nay\nGió rét có về\nLòng người có lắm chua cay\nTa như con thuyền\nNgược xuôi đi đó đây\nTìm em nào thấy\nLối cũ có còn\nChiều loang nắng hay mưa rơi\nBến cũ có còn\nNgười lặng đứng ngóng ra khơi\nHay ra đi rồi biền biệt\nXa xa khắp nơi\nCho mộng qua đời\nNgày nao quen nhau\nNgỡ đời mãi mãi có nhau\nNgày nay xa nhau\nÂm thầm nước vẫn qua cầu\nNgười hỡi về đâu\nĐêm nay gió mưa dãi dầu\nNgười ơi về đâu\nTìm nhau trong mơ\nTrong lời ca trong tiếng tơ\nTìm trong đêm mưa\nTrong ngày nắng cháy xa mờ\nNgười vẫn tìm nhau\nTrong duyên kiếp không mong chờ\nNgười đã như mơ\nTiếng hát tiếng cười\nCòn đâu đó trong đêm nay\nGió rét có về\nLòng người có lắm chua cay\nTa như con thuyền\nNgược xuôi đi đó đây\nTìm em nào thấy\nLối cũ có còn\nChiều loang nắng hay mưa rơi\nBến cũ có còn\nNgười lặng đứng ngóng ra khơi\nHay ra đi rồi biền biệt\nXa xa khắp nơi\nCho mộng qua đời\nNgày nao quen nhau\nNgỡ đời mãi mãi có nhau\nNgày nay xa nhau\nÂm thầm nước vẫn qua cầu\nNgười hỡi về đâu\nĐêm nay gió mưa dãi dầu\nNgười ơi về đâu\nTìm nhau trong mơ\nTrong lời ca trong tiếng tơ\nTìm trong đêm mưa\nTrong ngày nắng cháy xa mờ\nNgười vẫn tìm nhau\nTrong duyên kiếp không mong chờ\nNgười đã như mơ\nNgười vẫn tìm nhau\nTrong duyên kiếp không mong chờ\nNgười đã như mơ\nNgười vẫn tìm nhau\nTrong duyên kiếp không mong chờ\nNgười đã như mơ', 0, 0, 0, 'NguoiDaNhuMo-NgocHan-4654893.mp3'),
(31, 'Buồn Làm Chi Em Ơi', 'Hoài Lâm', '2022-10-23 20:38:04', 'Trữ tình & bolero', 'Việt Nam', 'Buồn làm chi em ơi lá xanh rồi cũng phai màu\nNgỡ duyên mình bền lâu ai ngờ lại xa cách nhau\nTrăng treo trên mái đầu, tâm tư nên âu sầu\nQua bao nhiêu dãi dầu mà lại nỡ qua cầu sang ngang\n\nBuồn làm chi em ơi hết duyên, phận cũng lỡ làng\nTiếc một đời xơ xác, ngỡ ngàng chuyện tình trái ngang\nAi gieo bao phũ phàng, cho hoa kia úa tàn\nThương số kiếp bẽ bàng rồi cứ trách mình quá vội vàng.\n\nBuồn làm chi em ơi, xót xa xin gửi lên trời\nChờ ngày mưa thôi rơi, mang nỗi sầu lìa xa tầm với\nĐời còn bao tương lai, lỡ sai vẫn kịp quay lại\nDù thời gian phôi phai, xin gói vào một tiếng thở dài.\n\nBuồn làm chi em ơi, nắng mưa nào bởi do mình\nTất cả là Thiên Ý, nên tình đành phải dở dang\nXin mang theo kỷ niệm, thêm bao nhiêu nỗi niềm\nTheo hoa rơi bên thềm và giữ mãi tận đáy con tim.', 0, 0, 0, 'BuonLamChiEmOi1-HoaiLam-6297318.mp3'),
(32, 'Người Thương Kẻ Nhớ', 'Phương Anh', '2022-10-23 20:39:03', 'Trữ tình & bolero', 'Việt Nam', 'Anh đi rồi, ngậm ngùi tôi ở lại\nĐêm bóng dài, nghe lạnh đầy bờ vai\nNgười đi vương nỗi nhớ\nNgười ở lại mang nỗi chờ\n\nNgõ hồn cô quạnh bơ vơ\nChỉ còn lại một vần thơ\nAnh đi rồi, nửa hồn tôi khờ dại\nTrăn trở hoài những kỷ niệm chưa phai\n\nNgày tôi anh gặp gỡ\nNgày tạ từ tay vẫy chào\nMềm lòng cặp nhạn xa nhau\nBởi giòng đời tựa sóng dâng cao\n\nAnh ra đi, nơi trời xa xứ lạ\nNhắn gửi gì về miền đất quê ta\nAnh vô tư hay là anh còn nhớ\nNhững con đường tình tựa ngày qua\n\nAnh đi rồi, có nghĩa là xa xôi.\nTôi ngóng chờ cũng chỉ là chờ thôi\nLàm sao ngăn được bước\n\nNgười ở lại chung hướng đời\nTình mình đành chia phôi\nMắt lệ buồn, tuôn mặn bờ môi.', 0, 0, 0, 'NguoiThuongKeNho-PhuongAnh-5248978.mp3'),
(33, 'Mai Anh Đi Rồi', 'Hồng Phượng', '2022-10-23 20:40:20', 'Trữ tình & bolero', 'Việt Nam', 'Mai anh đi rồi còn ai vuốt tóc những khi em hờn giỗi\nMai anh đi rồi còn ai dìu bước những khi em tan trường\nMai anh đi rồi, mai anh đi rồi\nChỉ còn lại đây với đêm ghế đá buồn công viên\n\nCon đường vào lồng phố khuya xanh xao\nKhi có những ngày mình mặn nồng bên nhau\nThôi mai cách xa nhau rồi\nCòn đêm nay nữa thôi mai anh lên đường gió sương\n\nThương em những ngày hai đứa\nHẹn hò vai sát vai đi bên nhau tình chan chứa\nXin anh hãy vui đêm này\nChuyện tình yêu chúng ta đêm em không bao giờ lãng quên\n\nEm xin giữ lời đã hứa ngày nào tan chiến chinh duyên đôi ta sẽ dài lâu\nMai anh đi rồi còn ai bắt bướm để cho em đùa giỡn\nMai anh đi rồi còn ai ngồi đếm tiếng mưa rơi lạnh lùng\nMai anh đi rồi mai anh đi rồi trả lại anh mến yêu\n\nTừng đêm vàng khói thuốc trên tay\nÂn tình nào chẳng có men chua cay\nGiây phút xa rồi mình còn gì đêm nay', 0, 0, 0, 'MaiAnhDiRoi-HongPhuong-6284200.mp3'),
(34, 'Má Thương Con Hoài', 'Tố My', '2022-10-23 20:41:21', 'Trữ tình & bolero', 'Việt Nam', 'Má ơi nuôi con\nMá khổ trăm bề\nTừ ngày bầu bì nghén thai\nĐến khi lâm bồn\nQuặng đau khôn xiết\nTừ ngày tập bò biết đi\nĐến khi nên người\nBước chân ra đời\nMá dặn mà dặn con nghe\nNgoài kia đời bao giông gió\nPhải lo tu thân giữ gìn\nPhải luôn yêu thương gia đình\nĐời dù có nghèo hay sang\nThì con ơi nhớ mấy câu\nMá thương con hoài\nĐể hôm nay chân bước về\nQua hàng sầu đâu\nMá đâu rồi bếp lạnh hoang\nKhông than không dầu\nMá đâu rồi giật mình\nKhói nhòe nhang cay\nNgười đi đã mấy năm nay\nLòng con ngày đêm thương nhớ\nMá ơi con về\nMà má nơi đâu\nMá ơi nuôi con\nMá khổ trăm bề\nTừ ngày bầu bì nghén thai\nĐến khi lâm bồn\nQuặng đau khôn xiết\nTừ ngày tập bò biết đi\nĐến khi nên người\nBước chân ra đời\nMá dặn mà dặn con nghe\nNgoài kia đời bao giông gió\nPhải lo tu thân giữ gìn\nPhải luôn yêu thương gia đình\nĐời dù có nghèo hay sang\nThì con ơi nhớ mấy câu\nMá thương con hoài\nĐể hôm nay chân bước về\nQua hàng sầu đâu\nMá đâu rồi bếp lạnh hoang\nKhông than không dầu\nMá đâu rồi giật mình\nKhói nhòe nhang cay\nNgười đi đã mấy năm nay\nLòng con ngày đêm thương nhớ\nMá ơi con về\nMà má nơi đâu\nMá ơi con về\nMà má nơi đâu', 0, 0, 0, 'MaThuongConHoai-ToMy-7776198.mp3'),
(35, 'Tôi Xa Ngoại Ô', 'Ngọc Phụng', '2022-10-23 20:42:18', 'Trữ tình & bolero', 'Việt Nam', 'Tôi xa ngoại ô giữa màn đêm tàn tro\nGiữa đường xưa ngày nao dìu lối em đi\nTiếng mưa rơi đêm ngày\nTiếng chuông ngân vơi đầy\nNgoại ô sương gió hoang lạnh liêu trai\nĐêm nay ngoại ô khép lại trong mộng mơ\nNhững tàu đêm đội mưa vào lối năm xưa\nLối trăng soi bóng hình\nXác thân đôi nhân tình\nNgoại ô tôi vẫn chưa vơi nỗi niềm\nĐêm nay ngoại ô còn bao nhiêu lời yêu\nLời đầu môi, lời nói cho nhau qua thời gian\nTình yêu người muôn hướng\nCàng yêu càng vất vưởng\nTôi xin giã từ đầy bao đắng cay\nCho nên nhiều đêm giữa ngoại ô buồn tênh\nNgồi vàng tay mồi thuốc gom suy tư vào tim\nTình yêu đầy dan díu\nNgười đi buồn chăn chiếu\nYêu chi để cho lòng xót xa nhiều\nĐêm nay ngồi đây quán trọ sương mù vây\nVũ trụ men rượu cay buồn hết đêm nay\nThế gian đây như thường\nGói tâm tư lên đường\nNgoại ô u uất đêm thâu chán chường\nĐêm nay ngoại ô còn bao nhiêu lời yêu\nLời đầu môi, lời nói cho nhau qua thời gian\nTình yêu người muôn hướng\nCàng yêu càng vất vưởng\nTôi xin giã từ đầy bao đắng cay\nCho nên nhiều đêm giữa ngoại ô buồn tênh\nNgồi vàng tay mồi thuốc gom suy tư vào tim\nTình yêu đầy dan díu\nNgười đi buồn chăn chiếu\nYêu chi để cho lòng xót xa nhiều\nĐêm nay ngồi đây quán trọ sương mù vây\nVũ trụ men rượu cay buồn hết đêm nay\nThế gian đây như thường\nGói tâm tư lên đường\nNgoại ô u uất đêm thâu chán chường\nThế gian đây như thường\nGói tâm tư lên đường\nNgoại ô u uất đêm thâu chán chường\nThế gian đây như thường\nGói tâm tư lên đường\nNgoại ô u uất đêm thâu chán chường\nThế gian đây như thường\nGói tâm tư lên đường\nNgoại ô u uất đêm thâu chán chường', 0, 0, 0, 'ToiXaNgoaiO-NgocPhung-7564953.mp3'),
(36, 'Tìm Đâu Bến Đỗ', 'Lưu Ánh Loan', '2022-10-23 20:43:35', 'Trữ tình & bolero', 'Việt Nam', 'Khi xưa yêu thương một người\nMà người đành tâm dối gian\nCon tim đã trao anh rồi\nMà anh chỉ hứa trên môi\nThuyền yêu xa bến\nBơ vơ lạc lõng giữa dòng\nEm ôm đắng cay hỏi lòng\nTình mình có bến hay không\nHôm nay bên em một người\nThề nguyện dâng hết thương yêu\nTrao em sắt son muôn đời\nTình nồng không để phai phôi\nNgười đâu hay biết\nTim em héo khô hững hờ\nAnh thương nói sao cho vừa\nMà em chẳng nguôi chuyện xưa\nEm sợ yêu\nSợ sau ấm êm nuông chiều\nSau bao ước mơ thật nhiều\nLà đêm khắc khoải cô liêu\nVì em không muốn\nMang đau đớn thêm một lần\nNên tim vẫn luôn ngại ngần\nVẫn e một ngày tình xa tay với\nLẻ loi giữa đời\nThì tội tình lắm người ơi\nPhân vân suy tư một mình\nThuyền tình biết đỗ bến nao\nHôm nay yêu thương ngọt ngào\nNgày mai biết sẽ ra sao\nTình mong manh quá\nPhai nhanh như nắng chiều tà\nĐêm nghe lá khô rơi là\nTình theo cơn gió tình xa\nHôm nay bên em một người\nThề nguyện dâng hết thương yêu\nTrao em sắt son muôn đời\nTình nồng không để phai phôi\nNgười đâu hay biết\nTim em héo khô hững hờ\nAnh thương nói sao cho vừa\nMà em chẳng nguôi chuyện xưa\nEm sợ yêu\nSợ sau ấm êm nuông chiều\nSau bao ước mơ thật nhiều\nLà đêm khắc khoải cô liêu\nVì em không muốn\nMang đau đớn thêm một lần\nNên tim vẫn luôn ngại ngần\nVẫn e một ngày tình xa tay với\nLẻ loi giữa đời\nThì tội tình lắm người ơi\nPhân vân suy tư một mình\nThuyền tình biết đỗ bến nao\nHôm nay yêu thương ngọt ngào\nNgày mai biết sẽ ra sao\nTình mong manh quá\nPhai nhanh như nắng chiều tà\nĐêm nghe lá khô rơi là\nTình theo cơn gió tình xa\nTình mong manh quá\nPhai nhanh như nắng chiều tà\nĐêm nghe lá khô rơi là\nTình theo cơn gió tình xa', 0, 0, 0, 'TimDauBenDo-LuuAnhLoan-7784127.mp3'),
(37, 'Duyên Phận', 'Như Quỳnh', '2022-10-23 20:46:04', 'Trữ tình & bolero', 'Việt Nam', 'Phận là con gái\nChưa một lần yêu ai\nNhìn về tương lai\nMà thấy như sông rộng đường dài\nCảnh nhà neo đơn\nBầy em chưa lớn\nTrĩu đôi vai gánh nhọc nhằn\nThầy mẹ thương em\nNhờ tìm người se duyên\nLòng cầu mong em đậu bến\nCho yên một bóng thuyền\nLứa đôi tình duyên\nCòn chưa lưu luyến\nSợ người ta đến\nEm khóc sau bao lời khuyên\nChưa yêu lần nao\nBiết ra làm sao\nBiết trong tình yêu như thế nào\nSông sâu là bao\nNào đo được đâu\nLòng người ta ai biết có dài lâu\nQua bao thời gian\nSống trong bình an\nLỡ yêu người ta gieo trái ngang\nNông sâu tùy sông\nLàm sao mà trông\nChưa đổ bến\nBiết nơi nào đục trong\nRồi người ta đến\nTheo họ hàng đôi bên\nMột ngày nên duyên\nMột bước em nên người vợ hiền\nBỏ lại sau lưng\nBầy em ngơ ngác\nĐứng trông theo mắt đượm buồn\nThầy mẹ vui hơn\nMà lệ tràn rưng rưng\nDặn dò con yêu phải sống\nTheo gia đạo bên chồng\nBước qua dòng sông\nHỏi từng con sóng\nĐời người con gái\nKhông muốn yêu ai được không\nChưa yêu lần nao\nBiết ra làm sao\nBiết trong tình yêu như thế nào\nSông sâu là bao\nNào đo được đâu\nLòng người ta ai biết có dài lâu\nQua bao thời gian\nSống trong bình an\nLỡ yêu người ta gieo trái ngang\nNông sâu tùy sông\nLàm sao mà trông\nChưa đổ bến\nBiết nơi nào đục trong\nRồi người ta đến\nTheo họ hàng đôi bên\nMột ngày nên duyên\nMột bước em nên người vợ hiền\nBỏ lại sau lưng\nBầy em ngơ ngác\nĐứng trông theo mắt đượm buồn\nThầy mẹ vui hơn\nMà lệ tràn rưng rưng\nDặn dò con yêu phải sống\nTheo gia đạo bên chồng\nBước qua dòng sông\nHỏi từng con sóng\nĐời người con gái\nKhông muốn yêu ai được không', 0, 0, 0, 'Duyen-Phan-Nhu-Quynh.mp3'),
(38, 'Xin Còn Gọi Tên Nhau', 'Chế Linh', '2022-10-23 20:46:48', 'Trữ tình & bolero', 'Việt Nam', 'Bài hát: Xin Còn Gọi Tên Nhau\nCa sĩ: Chế Linh\nTiếng hát bay trên ..\nThành phố bâng khuâng\nChiều đong đưa những\nBước.. chân đau mòn\nChợt nghe mùa thu\nBay trên trời không\nCòn ai giữa ...\nMênh mông đời mình\nNỗi đau ..\nVùi lấp...\nTrên tuổi thơ...\nPhố vắng hoang vu\nTừ lúc em đi\nRồi trong mưa gió\nBiết ai vỗ về\nBàn tay nào đưa\nEm trong lần vui\nBằng những tiếng\nChim non thì thầm\nCho ngày tháng\nƯu phiền em quên...\nTình trong..... cơn ngủ mê...\nRồi phai\nTrên hàng mi\nChợt khi mình nhớ về\nMộng thành mây bay đi\nCòn gì\nTrên đôi tay\nNên thầm hờn dỗi mình\nCho tình\nCàng thêm say\nTiếng hát ru em\nCòn nuối trên môi\nLời nào gian dối\nCũng xin qua rồi\nĐể lỡ ngày sau\nKhi ta cần nhau\nCòn nuôi chút\nÊm vui ngày đầu\nCho mình nhớ\nKêu thầm tên nhau\nTiếng hát bay trên ..\nThành phố bâng khuâng\nChiều đong đưa những\nBước.. chân đau mòn\nChợt nghe mùa thu\nBay trên trời không\nCòn ai giữa ...\nMênh mông đời mình\nNỗi đau ..\nVùi lấp...\nTrên tuổi thơ...\nPhố vắng hoang vu\nTừ lúc em đi\nRồi trong mưa gió\nBiết ai vỗ về\nBàn tay nào đưa\nEm trong lần vui\nBằng những tiếng\nChim non thì thầm\nCho ngày tháng\nƯu phiền em quên...\nTình trong..... cơn ngủ mê...\nRồi phai\nTrên hàng mi\nChợt khi mình nhớ về\nMộng thành mây bay đi\nCòn gì\nTrên đôi tay\nNên thầm hờn dỗi mình\nCho tình\nCàng thêm say\nTiếng hát ru em\nCòn nuối trên môi\nLời nào gian dối\nCũng xin qua rồi\nĐể lỡ ngày sau\nKhi ta cần nhau\nCòn nuôi chút\nÊm vui ngày đầu\nCho mình nhớ\nKêu thầm tên nhau\nĐể lỡ ngày sau\nKhi ta cần nhau\nCòn nuôi chút\nÊm vui ngày đầu\nCho mình nhớ\nKêu thầm tên nhau\nĐể lỡ ngày sau\nKhi ta cần nhau\nCòn nuôi chút\nÊm vui ngày đầu\nCho mình nhớ\nKêu thầm tên nhau\nĐể lỡ ngày sau\nKhi ta cần nhau\nCòn nuôi chút\nÊm vui ngày đầu\nCho mình nhớ\nKêu thầm tên nhau', 0, 0, 0, 'Xin-Con-Goi-Ten-Nhau-Che-Linh.mp3'),
(39, 'Ăn Năn', 'Giao Linh', '2022-10-23 21:00:40', 'Trữ tình & bolero', 'Việt Nam', 'Bài hát: Ăn Năn\nCa sĩ: Giao Linh\nNgày mình yêu nhau\nHai đứa ước mơ trầu cau\nEm đâu có ngờ\nRằng hai đứa xa nhau\nGiờ buồn không anh\nBiết mộng xưa chẳng thành\nEm tin không phải mình\nMà vì đời chia rẽ.\nChiều buồn trên mi\nHai đứa giữa cơn hè đi\nYêu thương kéo dài\nNgày hai đứa chia tay\nMột lần bên nhau\nCũng làm yêu suốt đời\nTrông cơn mê đắm này\nLà dấu buồn ăn năn.\nSóng gió cuốn tới\nLúc tình yêu mất rồi\nĐam mê đi hoang\nTrên vùng trăn trối... buồn\nBánh xe tình yêu\nMười năm chưa đến nơi\nNgày xưa cho đến sau\nTình yêu luôn đớn đau\nNước mắt nuối tiếc\nChảy đầy trong đáy hồn\nƯu tư em mang\nTheo vòng tay rã rời\nNhớ thương từng đêm\nVề phanh phui vết đau\nNgày vui đi quá mau\nNgày buồn sao kéo....\nDài....\nNgày mình yêu nhau\nHai đứa cũng không giàu sang\nEm đâu có ngờ\nTình yêu chiếc khăn tang\nĐường trần đêm đêm\nMắt buồn lo tủi hờn\nLang thang trên lối mòn\nVì đời không tô son.\nNgày đầu yêu nhau\nHai đứa ước mơ trầu cau\nEm đâu có ngờ\nRằng hai đứa xa nhau\nMột lần bên nhau\nCũng làm yêu suốt đời\nTrông cơn mê đắm này\nLà dấu buồn ăn năn!\nSóng gió cuốn tới\nLúc tình yêu mất rồi\nĐam mê đi hoang\nTrên vùng trăn trối... buồn\nBánh xe tình yêu\nMười năm chưa đến nơi\nNgày xưa cho đến sau\nTình yêu luôn đớn đau\nNước mắt nuối tiếc\nChảy đầy trong đáy hồn\nƯu tư em mang\nTheo vòng tay rã rời\nNhớ thương từng đêm\nVề phanh phui vết đau\nNgày vui đi quá mau\nNgày buồn sao kéo....\nDài....\nNgày mình yêu nhau\nHai đứa cũng không giàu sang\nEm đâu có ngờ\nTình yêu chiếc khăn tang\nĐường trần đêm đêm\nMắt buồn lo tủi hờn\nLang thang trên lối mòn\nVì đời không tô son.\nNgày đầu yêu nhau\nHai đứa ước mơ trầu cau\nEm đâu có ngờ\nRằng hai đứa xa nhau\nMột lần bên nhau\nCũng làm yêu suốt đời\nTrông cơn mê đắm này\nLà dấu buồn ăn năn!', 0, 0, 0, 'An-Nan-Giao-Linh.mp3'),
(40, 'Cô Đơn', 'Quỳnh Lan', '2022-10-23 21:08:08', 'Trữ tình & bolero', 'Việt Nam', 'Bài Hát: Cô Đơn\nCa sĩ: Quỳnh Lan\nHạnh phúc....\nNhư đôi chim uyên\nTung bay\nNgập trời nắng ấm\nHạnh phúc\nNhư sương ban mai\nLong lanh\nĐậu cành lá thắm.\nTình yêu\nMột thoáng ...\nLên ngôi\nNhẹ nhàng như áng\nMây trôi\nDịu dàng như ánh\nTrăng soi\nÊm êm hương yêu\nDâng... trong hồn tôi.\nNghe...\nNhư chim ngàn phiêu lãng\nTheo mây trời lang thang\nRong chơi cùng năm tháng.\nÔi... đêm đêm cùng tiếng hát\nCho vơi niềm thương nhớ\nCòn gì... cho ước mơ.\nNgười hỡi .....\nCho tôi quên đi\nBao nhiêu kỷ niệm\nXa xưa\nNgười hỡi ....\nCho tôi quên đi\nBao nhiêu mộng đẹp\nNên thơ.\nTình yêu đã chết......\nTrong tôi....\nNụ cười đã tắt.....\nTrên môi\nChỉ còn tiếc nuối\nKhôn nguôi\nCô đơn bơ vơ\nTiếng hát lạc loài.....\nNghe...\nNhư chim trời phiêu lãng\nTheo mây trời lang thang\nRong chơi cùng năm tháng.\nÔi... đêm đêm cùng tiếng hát\nCho vơi niềm thương nhớ\nCòn gì... cho ước... mơ...\nNgười hỡi .....\nCho tôi quên đi\nBao nhiêu kỷ niệm\nXa xưa\nNgười hỡi ....\nCho tôi quên đi\nBao nhiêu mộng đẹp\nNên thơ.\nTình yêu đã chết......\nTrong tôi....\nNụ cười đã tắt.....\nTrên môi\nChỉ còn\nTiếc nuối\nKhôn nguôi\nCô đơn bơ vơ\nTiếng hát.....\nLạc loài.....', 0, 0, 0, 'Co-Don-Quynh-Lan.mp3'),
(41, 'Mèo Hoang', 'Tuấn Vũ', '2022-10-23 21:10:20', 'Trữ tình & bolero', 'Việt Nam', 'Bài Hát: Mèo Hoang\nCa sĩ: Tuấn Vũ\nCó phải em về....\nTrong đêm nay\nBước thấp bước cao\nNgã nghiêng\nTrên đời này .\nLệch vai áo hoa\nPhai màu son đôi môi\nNhạt nhòa...\nNghe buồn đau lên xót.. xa ....\nTrang điểm cho người\nVui đêm nay\nChén chú chén anh\nRượu vơi đi lại đầy .\nNào ai biết ai\nSao lại ôm nhau như người tình\nĐôi bàn tay thú phiêu linh .\nEm... gái quê nơi đồng ruộng\nNắng cháy\nKhoác xiêm y\nEm thành người phố thị .\nCơm áo gạo tiền\nXui em biết dối gian\nEm bước chân xuống đời\nThành mèo hoang .\nCó phải đêm buồn\nĐêm lang thang\nĐốt cháy trái tim\nĐời qua mau bàng hoàng .\nNgày mai bước đi\nMang nỗi đau thân phận bọt bèo\nTiên đời em cũng mang theo .\nCó phải em về....\nTrong đêm nay\nBước thấp bước cao\nNgã nghiêng\nTrên đời này .\nLệch vai áo hoa\nPhai màu son đôi môi\nNhạt nhòa...\nNghe buồn đau lên xót.. xa ....\nTrang điểm cho người\nVui đêm nay\nChén chú chén anh\nRượu vơi đi lại đầy .\nNào ai biết ai\nSao lại ôm nhau như người tình\nĐôi bàn tay thú phiêu linh .\nEm... gái quê nơi đồng ruộng\nNắng cháy\nKhoác xiêm y\nEm thành người phố thị .\nCơm áo gạo tiền\nXui em biết dối gian\nEm bước chân xuống đời\nThành mèo hoang .\nCó phải đêm buồn\nĐêm lang thang\nĐốt cháy trái tim\nĐời qua mau bàng hoàng .\nNgày mai bước đi\nMang nỗi đau thân phận bọt bèo\nTiên đời em cũng mang theo .\nNgày mai bước đi\nMang nỗi đau thân phận bọt bèo\nTiên đời......\nEm cũng mang.... theo.....\nNgày mai bước đi\nMang nỗi đau thân phận bọt bèo\nTiên đời......\nEm cũng mang.... theo.....\nNgày mai bước đi\nMang nỗi đau thân phận bọt bèo\nTiên đời......\nEm cũng mang.... theo.....', 0, 0, 0, 'Meo-Hoang-Tuan-Vu (1).mp3'),
(42, 'Áo Em Chưa Mặc Một Lần', 'Trường Vũ', '2022-10-23 21:10:44', 'Trữ tình & bolero', 'Việt Nam', 'Bài hát: Áo Em Chưa Mặc Một Lần\nCa sĩ: Trường Vũ\nTôi nghèo ....\nEm cũng chẳng cao sang....\nTay trắng ...\nCùng nhau.....\nDệt mộng.... vàng\nHôn lễ nghèo.... nàn\nEm chỉ ước\nCặp áo thêu hoa\nKhỏi bẽ..... bàng\nTôi với nàng\nHai đứa...\nNguyện yêu nhau\nTha thiết từ đây\nCho đến...\nNgày bạc đầu\nĐể giao ước ...\nTôi trao....\nNàng nhẫn cưới\nEm cũng tặng tôi\nKhăn hồng\nThêu cành hoa mai\nTôi vốn nghèo\nEm cũng\nChẳng cao sang\nTay trắng cùng nhau\nHai đứa\nDệt mộng vàng\nNgày hôn lễ....\nEm không... đòi\nChâu báu\nMơ ước một đôi\nÁo thêu\nĐể nhớ duyên đầu\nNgờ đâu ....\nDây đứt lìa đàn\nNụ hoa ....\nĐang thắm vội tàn\nChưa vui ....\nĐã sầu chia phôi\nVội đi\nBỏ đôi áo mới\nAi mặc\nBây giờ em ơi?\nTôi thẫn thờ\nNghe tiếng\nHàng thông reo\nThương quá là thương\nKhi nắng\nNgã về chiều\nNhìn đôi áo\nTôi thương\nVề... dĩ vãng\nNhư vẫn còn trông\nThấy em\nMặc lễ tơ hồng\nTôi thẫn thờ\nNghe tiếng\nHàng thông reo\nThương quá là thương\nKhi nắng\nNgã về chiều\nNhìn đôi áo\nTôi thương\nVề... dĩ vãng\nNhư vẫn còn trông\nThấy em\nMặc lễ tơ hồng\nNhìn đôi áo\nTôi thương\nVề... dĩ vãng\nNhư vẫn còn trông\nThấy em\nMặc lễ tơ hồng\nNhìn đôi áo\nTôi thương\nVề... dĩ vãng\nNhư vẫn còn trông\nThấy em\nMặc lễ tơ hồng', 0, 0, 0, 'Ao-Em-Chua-Mac-Mot-Lan-Truong-Vu.mp3'),
(43, 'Tình Bolero', 'Hà Vân, Vũ Quốc Việt', '2022-10-23 21:11:39', 'Trữ tình & bolero', 'Việt Nam', 'Bài Hát: Tình Bolero\nCa sĩ: Hà Vân, Vũ Quốc Việt\nNhững đêm mưa buồn\nGió buốt lạnh\nMiền ngoại ô tuổi thơ.. ngây....\nNhạc Bolero\nNghe sao ngọt quá\nRâm rang câu hát\nTiếng lòng ai kia\nThao thức nhớ\nNgười phương xa\nĐêm hè\nMẹ ngóng.. trông... con\nĐến nay vẫn còn\nCâu hát buồn\nGiọng bolero mãi ngâng... nga\nThành phố, đồng quê\nHay miền núi\nNghe trong câu hát\nCó tình quê.. hương\nCâu hát có lời yêu thương\nNgọt ngào ta hát ....\nCho nhau...\nHãy hát hãy hát ru tình yêu\nHát lên cho ngày vui\nHát ru khi u... sầu...\nHãy hát hãy hát ru tình ta\nHát ru thân phận ai\nHát cho nhau ngày mai.\nĐời còn hợp tan\nBên nhau ta cùng ca hát\nDù thời gian qua\nNhưng Bolero vẫn mãi....\nCòn vang.\nĐến nay vẫn còn\nCâu hát buồn\nGiọng bolero mãi ngâng.. nga\nThành phố, đồng quê\nHay miền núi\nNghe trong câu hát\nCó tình quê hương\nCâu hát có lời yêu thương\nNgọt ngào ta hát ....\nCho nhau\nHãy hát hãy hát ru tình yêu\nHát lên cho ngày vui\nHát ru khi u... sầu...\nHãy hát hãy hát ru tình ta\nHát ru thân phận ai\nHát cho nhau ngày mai.\nĐời còn hợp tan\nBên nhau ta cùng ca hát\nDù thời gian qua\nNhưng Bolero vẫn mãi....\nCòn vang.\nHãy hát hãy hát ru tình yêu\nHát lên cho ngày vui\nHát ru khi u... sầu...\nHãy hát hãy hát ru tình ta\nHát ru thân phận ai\nHát cho nhau ngày mai.\nĐời còn hợp tan\nBên nhau ta cùng ca hát\nDù thời gian qua\nNhưng Bolero vẫn mãi....\nCòn vang.\nTình......\nBolero.......\nTình.....\nBolero......', 0, 0, 0, 'Tinh-Bolero-Ha-Van-Vu-Quoc-Viet.mp3'),
(44, 'Đập Vỡ Cây Đàn', 'Quang Lê', '2022-10-23 21:12:03', 'Trữ tình & bolero', 'Việt Nam', 'Bài Hát: Đập Vỡ Cây Đàn\nCa Sĩ: Quang Lê\nĐập vỡ cây đàn\nGiận đời đập vỡ cây đàn\nNgười ơi người ơi\nTình ơi tình ơi\nĐập vỡ cây đàn giận đời\nBạc trắng như vôi\nGiận người điên đảo\nQuên lời\nĐập vỡ cây đàn giận người\nCon gái yêu đàn\nBuồn ơi buồn ơi\nLàm sao để nguôi\nĐập vỡ cây đàn giận người\nĐổi trắng thay đen\nGiận đời trở như bàn tay\nChuyện ngày qua\nTôi gặp người con gái\nMang giọng ca thật buồn\nEm bảo tôi rằng\nAnh đi học đàn\nĐể đàn theo lúc em ca\nNhững ngày hoa mộng đời ta\nTôi yêu nàng\nNên vội vàng lên tỉnh\nĐi tìm theo học đàn\nSau một năm trường\nTôi trở về quê hương\nNhưng người con gái\nNgày ấy đã đi rồi\nTôi hỏi thăm dò từng người\nTrong xóm tin nàng\nNàng đâu nàng đâu\nNàng đâu nàng đâu\nNgười báo tin buồn\nNàng gặp nhạc sĩ vang danh\nRồi cùng xây đắp gia đình\nTôi xót thương nàng\nVà rồi tôi khóc thương mình\nĐời ơi còn chi\nĐàn ơi biệt ly\nĐập vỡ cây đàn giận người\nĐổi trắng thay đen\nGiận đời trở như bàn tay\nChuyện ngày qua\nTôi gặp người con gái\nMang giọng ca thật buồn\nEm bảo tôi rằng\nAnh đi học đàn\nĐể đàn theo lúc em ca\nNhững ngày hoa mộng đời ta\nTôi yêu nàng\nNên vội vàng lên tỉnh\nĐi tìm theo học đàn\nSau một năm trường\nTôi trở về quê hương\nNhưng người em gái\nNgày ấy đã đi rồi\nTôi hỏi thăm dò từng người\nTrong xóm tin nàng\nNàng đâu nàng đâu\nNàng đâu nàng đâu\nNgười báo tin buồn\nNàng gặp nhạc sĩ vang danh\nRồi cùng xây đắp gia đình\nTôi xót thương nàng\nVà rồi tôi khóc thương mình\nĐời ơi còn chi\nĐàn ơi biệt ly\nĐập vỡ cây đàn giận người\nĐổi trắng thay đen\nGiận đời trở như bàn tay\nĐập vỡ cây đàn giận người\nĐổi trắng thay đen\nGiận đời trở như bàn tay', 0, 0, 0, 'Dap-Vo-Cay-Dan-Quang-Le.mp3'),
(45, 'Sầu Tím Thiệp Hồng', 'Quang Lê , Lệ Quyên', '2022-10-23 21:12:38', 'Trữ tình & bolero', 'Việt Nam', 'Bài hát: Sầu Tím Thiệp Hồng\nCa sĩ: Quang Lê , Lệ Quyên\nTừ lúc quen nhau\nChưa nói một lời gì\nTỏ tình ta mến... nhau\nNhiều đêm ngắm sao\nMơ ước\nDuyên mình bền lâu\nSuốt đời tình khắc... sâu....\nNhớ thương đầy vơi\nMộng thấy\nAi mỉm cười\nLàn môi xinh tuyệt vời\nĐể rồi buồn ơi\nÁnh trăng soi còn đó\nVà nghe hơi gió\nBiết rằng\nMình vừa...... mơ....\nKhi yêu\nHồn như\nNở hoa xây mộng\nTuyệt vời\nNắm tương lai trong\nBàn tay\nMột câu nói... thôi.....\nĐôi khi gặp nhau\nMuốn khơi nhưng rồi\nLại thôi\nNói ra e ngại\nMặc theo gió trôi.\nHôm nay\nNhìn xe\nKết hoa xuôi ngược\nNẻo đường\nGửi thư trao cho\nNgười yêu\nVài câu luyến... thương....\nHân hoan hồn như\nNở hoa\nTrông chờ hồi âm\nĐắng cay trong lòng\nChỉ thấy thiệp hồng.\nChiều tím không mây\nĐường cũ bước lần về\nBuồn nghe day dứt... tim....\nNhìn xe kết hoa\nMàu trắng\nNgỡ rằng mình mơ\nPháo hồng nhuộm tiễn... đưa....\nLá thu chậm rơi\nTừng lá nghe buồn buồn\nTưởng bước ai tìm về\nMở rộng vòng tay\nĐón anh nhưng nào thấy\nSầu dâng lên tím\nBiết bao giờ cho.... khuây?\nHôm nay\nNhìn xe\nKết hoa xuôi ngược\nNẻo đường\nGửi thư trao cho\nNgười yêu\nVài câu luyến... thương.\nHân hoan hồn như\nNở hoa\nTrông chờ hồi âm\nĐắng cay trong lòng\nChỉ thấy thiệp hồng.\nChiều tím không mây\nĐường cũ bước lần về\nBuồn nghe day dứt tim\nNhìn xe kết hoa\nMàu trắng\nNgỡ rằng mình mơ\nPháo hồng nhuộm tiễn đưa\nLá thu chậm rơi\nTừng lá nghe buồn buồn\nTưởng bước ai tìm về\nMở rộng vòng tay\nĐón anh nhưng nào thấy\nSầu dâng lên tím\nBiết bao giờ cho... khuây?\nMở rộng vòng tay\nĐón anh nhưng nào thấy\nSầu dâng lên tím\nBiết bao giờ .....\nCho...... khuây......?', 0, 0, 0, 'Sau-Tim-Thiep-Hong-Quang-Le-Le-Quyen.mp3'),
(46, 'Phận Tơ Tằm', 'Tố My', '2022-10-23 21:13:04', 'Trữ tình & bolero', 'Việt Nam', 'Bài Hát: Phận Tơ Tằm\nCa sĩ: Tố My\nNgười có thương\nThân tôi nghệ sĩ\nThì đừng có thương\nNhư thương hại đời\nVà đừng có nghe\nKhi thiên hạ thường\nDèm pha tôi kiếp\nSướng.... ca...\nNgười đến đây\nĐêm đêm phòng trà\nĐèn màu kết hoa\nThương yêu mặn mà\nTôi xin người\nNhìn lên sân khấu\nHãy tin tôi hơn lời ca\nRượu nồng đó ....\nNgười đã say chưa\nÂn tình này\nSao không gắn bó\nĐời là những\nDòng nước vô tư\nTa là thuyền\nSóng đưa xa bờ\nNgười ngồi đó\nCòn có nghe tôi\nTâm tình này\nVươn lên đắm đuối\nNgười đừng trách\nMột kiếp cầm ca\nCon tằm nào\nKhông muốn vương tơ\nNgười nói đi\nNhư tim người nghĩ\nLàm nghề sướng ca\nTôi mang tội gì\nHọa là có chăng\nTôi mang tội đời\nLàm cho nhân thế\nSay.... mê....\nNgười nói đi\nCho tôi một lời\nRằng nghề xướng ca\nTôi không lạc loài\nTạ ơn người\nPhận tằm tôi muôn kiếp\nVương tơ cho đời vui...\nRượu nồng đó ....\nNgười đã say chưa\nÂn tình này\nSao không gắn bó\nĐời là những\nDòng nước vô tư\nTa là thuyền\nSóng đưa xa bờ\nNgười ngồi đó\nCòn có nghe tôi\nTâm tình đầy\nVươn lên đắm đuối\nNgười đừng trách\nMột kiếp cầm ca\nCon tằm nào\nKhông muốn vương tơ\nNgười nói đi\nNhư tim người nghĩ\nLàm nghề sướng ca\nTôi mang tội gì\nHọa là có chăng\nTôi mang tội đời\nLàm cho nhân thế\nSay... mê....\nNgười nói đi\nCho tôi một lời\nRằng nghề sướng ca\nTôi không lạc loài\nTạ ơn người\nPhận tằm tôi muôn kiếp.....\nVương tơ.. cho đời vui...\nNgười nói đi\nCho tôi một lời\nRằng nghề sướng ca\nTôi không lạc loài\nTạ ơn người\nPhận tằm tôi muôn kiếp.....\nVương tơ...\nCho đời... vui...', 0, 0, 0, 'Phan-To-Tam-To-My.mp3');
INSERT INTO `songs` (`id`, `name`, `singer`, `date`, `category`, `nation`, `lyric`, `listens`, `comments`, `downloads`, `file`) VALUES
(47, 'Trăm Nhớ Ngàn Thương', 'Quang Dũng', '2022-10-23 21:13:28', 'Trữ tình & bolero', 'Việt Nam', 'Bài Hát: Trăm Nhớ Ngàn Thương\nCa sĩ: Quang Dũng\nMất em rồi\nXa em rồi\nHoa đã tàn\nNhụy đã phai\nChiều hôm nay\nTrời thanh vắng\nAnh đi về\nVề với ai\nMột người đi\nMột người sầu\nNhìn hoa úa\nBuồn về mau\nĐôi chân mòn\nTìm dư âm hè phố vắng\nLòng còn thương\nTình còn nồng\nMà đêm nhớ\nNgày chờ mong\nBao thu rồi\nNhìn lá úa\nRơi ngoài sông ....\nCánh thư này\nKỷ niệm này\nTa đã tìm\nVề với nhau\nRồi hôm nay\nTàn mơ ước anh u sầu\nEm ở đâu ?\nChiều nay....\nMây đen giăng\nSầu đường về\nNhìn hoa rơi\nNão nề\nNgười ơi.. sao chẳng về\nCòn mong chi\nCâu thề\nGiận nhau\nSao không nói\nRa đi\nKhông một lời\nĐể buốt giá\nTim tôi\nAi ngờ\nChim trời\nVỗ cánh tung bay\nNgười đi\nĐể nhớ cho đời\nLàm sao\nTôi đến bên người\nBao giờ\nMây hồng đưa bước\nEm sang\nHay từ đây\nAnh dở dang\nTình hỡi\nChôn vào thiên thu\nMột người đi\nMột người sầu\nNhìn hoa úa\nBuồn về mau\nĐôi chân mòn\nTìm dư âm hè phố vắng\nLòng còn thương\nTình còn nồng\nMà đêm nhớ\nNgày chờ mong\nBao thu rồi\nNhìn lá úa\nRơi ngoài sông ....\nCánh thư này\nKỷ niệm này\nTa đã tìm\nVề với nhau\nRồi hôm nay\nTàn mơ ước anh u sầu\nEm ở đâu ?\nChiều nay....\nMây đen giăng\nSầu đường về\nNhìn hoa rơi\nNão nề\nNgười ơi sao chẳng về\nCòn mong chi\nCâu thề\nGiận nhau\nSao không nói\nRa đi\nKhông một lời\nĐể buốt giá\nTim tôi\nAi ngờ\nChim trời\nVỗ cánh tung bay\nNgười đi\nĐể nhớ cho đời\nLàm sao\nTôi đến bên người\nBao giờ\nMây hồng đưa bước\nEm sang\nHay từ đây\nAnh dở dang\nTình hỡi\nChôn vào.....\nThiên... thu.....', 0, 0, 0, 'Tram-Nho-Ngan-Thuong-Quang-Dung.mp3'),
(48, 'Sao Chưa Thấy Hồi Âm', 'Cẩm Ly', '2022-10-23 21:13:55', 'Trữ tình & bolero', 'Việt Nam', 'Bài Hát: Sao Chưa Thấy Hồi Âm\nCa sĩ: Cẩm Ly\nTheo năm tháng hoài mong\nThư gửi đi mấy lần\nĐợi .. hồi âm chưa thấy....\nAnh ơi nhớ rằng đây\nCòn có em đêm ngày\nHằng thương nhớ vơi đầy.\nNgày đi người đã hứa ....\nToàn những lời chan chứa\nCòn hơn gió hơn mưa.\nMỗi tuần một lần thư\nKể nghe chuyện sương gió\nKể nghe niềm ước mơ....\nNhưng anh vắng hồi thư\nHay là anh hững hờ\nHoặc là anh không nhớ\nEm đâu khác người xưa\nNgày lẫn đêm mong chờ\nTình yêu nói sao... vừa....\nTừ lâu đành xa vắng\nĐời trăm ngàn cay đắng\nHỏi anh biết hay chăng\nChỉ cần một hồi âm\nLà em mừng vui lắm\nCớ sao anh phụ... lòng...\nNgày xưa...\nAnh còn nhớ\nNàng Tô Thị\nBồng con ngóng trông\nThời gian\nĐã hoài công\nNgười thành đá\nNgàn kiếp yêu thương chồng\nNgày nay\nEm nào thấy\nLòng chân thành\nCủa tình thế nhân\nTìm.. đâu..\nTrong tình yêu\nĐược bền lâu\nĐể kiếp sau không sầu\nEm mơ ước làm sao\nCho trọn mối duyên đầu\nĐẹp lòng anh yêu dấu\nXưa Chức Nữ chàng Ngưu\nTừng đắng cay dãi dầu\nChờ Ô Thước bắt.. cầu\nCòn anh từ xa cách\nLàm em hờn em trách\nHỏi anh có hay không.\nMỏi mòn đợi hồi âm\nThềm hoa đành lẻ bóng\nNhớ thương anh ngập... lòng...\nNgày xưa...\nAnh còn nhớ\nNàng Tô Thị\nBồng con ngóng trông\nThời gian ...\nĐã hoài công\nNgười thành đá\nNgàn kiếp yêu thương chồng\nNgày nay...\nEm nào thấy\nLòng chân thành\nCủa tình thế nhân\nTìm.. đâu..\nTrong tình yêu\nĐược bền lâu\nĐể kiếp sau không sầu\nEm mơ ước làm sao\nCho trọn mối duyên đầu\nĐẹp lòng anh yêu dấu\nXưa Chức Nữ chàng Ngưu\nTừng đắng cay dãi dầu\nChờ Ô Thước bắt cầu\nCòn anh từ xa cách\nLàm em hờn em trách\nHỏi anh có hay không.\nMỏi mòn đợi hồi âm\nThềm hoa đành lẻ bóng\nNhớ thương anh ngập... lòng...\nMỏi mòn đợi hồi âm\nThềm hoa đành lẻ bóng....\nNhớ thương anh ngập... lòng...', 0, 0, 0, 'Sao-Chua-Thay-Hoi-Am-Cam-Ly.mp3'),
(49, 'Lệ Đá', 'Tuấn Vũ', '2022-10-23 21:14:20', 'Trữ tình & bolero', 'Việt Nam', 'Bài Hát: Lệ Đá\nCa Sĩ: Tuấn Vũ\nHỏi đá xanh rêu\nBao nhiêu tuổi đời\nHỏi gió phiêu du\nQua bao đỉnh trời\nHỏi những đêm sâu\nĐèn vàng héo hắt\nÁi ân bây giờ là nước mắt\nCuối hồn một thoáng\nNhớ mong manh\nThuở ấy tôi như\nCon chim lạc đàn\nXoải cánh cô đơn\nBay trong chiều vàng\nVà ước mơ sao\nTrời đừng bão tố\nĐể yêu thương\nCàng nhiều gắn bó\nTháng ngày là men say nguồn thơ\nTình yêu đã vỗ cánh rồi\nLà hoa rót mật cho đời\nChắt chiu kỷ niệm dĩ vãng\nEm nhớ gì không em ơi\nMầu áo thiên thanh\nThơ ngây ngày nào\nChìm khuất trong mưa\nMưa bay rạt rào\nĐọc lá thư xưa\nMột trời luyến tiếc\nNhớ môi em và màu mắt biếc\nSuối hẹn hò trăng xanh đầu non\nThuở ấy tôi như\nCon chim lạc đàn\nXoải cánh cô đơn\nBay trong chiều vàng\nVà ước mơ sao\nTrời đừng bão tố\nĐể yêu thương\nCàng nhiều gắn bó\nTháng ngày là men say nguồn thơ\nTình yêu đã vỗ cánh rồi\nLà hoa rót mật cho đời\nChắt chiu kỷ niệm dĩ vãng\nEm nhớ gì không em ơi\nMầu áo thiên thanh\nThơ ngây ngày nào\nChìm khuất trong mưa\nMưa bay rạt rào\nĐọc lá thư xưa\nMột trời luyến tiếc\nNhớ môi em và màu mắt biếc\nSuối hẹn hò trăng xanh đầu non\nĐọc lá thư xưa\nMột trời luyến tiếc\nNhớ môi em và màu mắt biếc\nSuối hẹn hò\nTrăng xanh đầu non', 0, 0, 0, 'Le-Da-Tuan-Vu.mp3'),
(50, 'Về Đâu Mái Tóc Người Thương', 'Quang Lê', '2022-10-23 21:14:49', 'Trữ tình & bolero', 'Việt Nam', 'Bài hát: Về Đâu Mái Tóc Người Thương\nCa sĩ: Quang Lê\nHồn lỡ sa vào ....\nĐôi mắt em\nChiều nao xõa tóc\nNgồi bên rèm\nThầm ước nhưng nào\nĐâu dám nói\nKhép tâm tư lại thôi\nĐường hoa vẫn chưa mở... lối...\nĐời lắm phong trần\nTay trắng.. tay\nTrời đông ngại gió\nLùa vai.. gầy...\nLầu kín trăng về\nKhông lối chiếu\nGác cao ngăn niềm yêu\nThì thôi mơ ước.. chi... nhiều....\nBên nhau\nSao tình xa vạn lý\nCách biệt mấy sơn khê\nNgày đi\nMắt em xanh biển sâu,\nMắt tôi rưng rưng sầu\nLặng nghe tiếng pháo\nTiễn ai qua cầu\nĐường phố muôn màu\nSao thiếu... em\nVề đâu làn tóc\nXõa bên... rèm\nLầu vắng không người\nSong khép kín\nNhớ em tôi gọi tên,\nChỉ nghe lá rơi thềm\nBên nhau\nSao tình xa vạn lý\nCách biệt mấy sơn khê\nNgày đi\nMắt em xanh biển sâu,\nMắt tôi rưng rưng sầu\nLặng nghe tiếng pháo\nTiễn ai qua cầu\nĐường phố muôn màu\nSao thiếu... em\nVề đâu làn tóc\nXõa bên... rèm\nLầu vắng không người\nSong khép kín\nNhớ em tôi gọi tên,\nChỉ nghe tiếng lá rơi.... thềm\nLầu vắng không người\nSong khép kín\nNhớ em tôi gọi tên,\nChỉ nghe.....\nTiếng.. lá.... rơi.... thềm......', 0, 0, 0, 'Ve-Dau-Mai-Toc-Nguoi-Thuong-Quang-Le.mp3'),
(51, 'Kiếp Đam Mê', 'Bằng Kiều', '2022-10-23 21:15:26', 'Trữ tình & bolero', 'Việt Nam', 'Bài Hát: Kiếp Đam Mê\nCa sĩ: Bằng Kiều\nTôi xin người\nCứ gian dối\nCho tôi tưởng\nNgười cũng yêu tôi\nNên tôi còn được\nThấy đời vui\nKhi cơn mưa\nMùa đông đang tới\nXin giã từ\nNgày tháng rong chơi\nĐôi tay này\nVẫn chờ mong\nCon tim này\nDù lắm long đong\nTôi yêu người\nBằng nỗi nghiệt oan\nKhông than van\nVà không trách oán\nCho tôi trọn\nMột kiếp đam mê ...\nÔi ....\nTôi ước mơ\nEm bỏ cuộc vui\nTrở về căn phòng này\nĐơn côi\nMôi em ru\nNỗi đau tuyệt vời\nKhi màn đêm\nPhủ lứa đôi\nLà thời gian\nCũng như ngừng trôi\nThương yêu này\nNgười hãy nhận lấy\nÔm tôi đi\nMôi hôn tràn đầy\nTrong tay người\nHồn sẽ cuồng say\nBao khốn khó\nVụt bay\nTôi không cần\nVà nghi ngại khi\nAi chê bai\nThân tôi khờ dại\nTôi yêu người\nHồn trắng tình trong\nTôi vẫn cứ\nĐợi mong ....\nTôi xin người\nCứ gian dối\nKhi tôi hỏi\nNgười có yêu tôi\nMay ra còn\nĐược chút tình vui\nKhi cơn mưa\nMùa đông đang tới\nTôi xin người\nCứ gian dối\nNhưng xin người\nĐừng lìa xa tôi!\nĐôi tay này\nVẫn chờ mong\nCon tim này\nDù lắm long đong\nTôi yêu người\nBằng nỗi nghiệt oan\nKhông than van\nVà không trách oán\nCho tôi trọn\nMột kiếp đam mê ...\nÔi ....\nTôi ước mơ\nEm bỏ cuộc vui\nTrở về căn phòng này\nĐơn côi\nMôi em ru\nNỗi đau tuyệt vời\nKhi màn đêm\nPhủ lứa đôi\nLà thời gian\nCũng như ngừng trôi\nThương yêu này\nNgười hãy nhận lấy\nÔm tôi đi\nMôi hôn tràn đầy\nTrong tay người\nHồn sẽ cuồng say\nBao khốn khó\nVụt bay\nTôi không cần\nVà nghi ngại khi\nAi chê bai\nThân tôi khờ dại\nTôi yêu người\nHồn trắng tình trong\nTôi vẫn cứ\nĐợi mong ....\nTôi xin người\nCứ gian dối\nKhi tôi hỏi\nNgười có yêu tôi\nMay ra còn\nĐược chút tình vui\nKhi cơn mưa\nMùa đông đang tới\nTôi xin người\nCứ gian dối\nNhưng xin người\nĐừng lìa xa tôi!\nTôi xin người\nCứ gian dối\nNhưng xin người\nĐừng lìa.. xa.... tôi....!', 0, 0, 0, 'Kiep-Dam-Me-Bang-Kieu.mp3'),
(52, 'Giọng Ca Dĩ Vãng', 'Như Quỳnh', '2022-10-23 21:15:49', 'Trữ tình & bolero', 'Việt Nam', 'Bài hát: Giọng Ca Dĩ Vãng\nCa sĩ: Như Quỳnh\nNgày xưa ....\nMỗi lần...\nEm buông tiếng hát\nThì anh ...\nTay phiếm ...\nNắn nót cung đàn\nTừng nhịp nhặt khoan\nAnh ru hồn theo tiếng tơ\nNhẹ dịu lời ca\nEm thăng trầm theo từng lúc\nVà rồi hờn yêu em\nKhi nào em hát sai\nEm nũng nịu cười\nNói sai là tại anh.\nNhưng...\nEm nuôi mộng ước về\nTương lai\nHoa mai giăng ngập\nNẻo đường em đi\nRồi em đành chối\nTiếng giao hoà\nTừ ly là tiếng thét\nĐau lòng sầu đơn lối.\nAi đang xây\nLầu cát vàng cao sang\nAi đem cung nhạc\nTiếng đàn gieo hoang\nLời ca ngày đó\nĐã xa rồi\nMà ai còn chuốt mãi\nCung đàn vọng về tim.\nGiờ đây ...\nMỗi lần ...\nEm buông tiếng hát\nThì ai ....\nThay thế ...\nNắn phím cung đàn\nTừng điệu nhặt khoan\nAi sẽ dìu theo tiếng em\nVà rồi hờn yêu em\nNay còn như ngày trước\nVà rồi tại ai\nTrong mỗi lần em hát sai\nCung lỡ giây chùng\nMấy ai đàn đừng sai.\nAi đang xây\nLầu cát vàng cao sang\nAi đem cung nhạc\nTiếng đàn gieo hoang\nLời ca ngày đó\nĐã xa rồi\nMà ai còn chuốt mãi\nCung đàn vọng về tim.\nGiờ đây ...\nMỗi lần ...\nEm buông tiếng hát\nThì ai ....\nThay thế ...\nNắn phím cung đàn\nTừng điệu nhặt khoan\nAi sẽ dìu theo tiếng em\nVà rồi hờn yêu em\nNay còn như ngày trước\nVà rồi tại ai\nTrong mỗi lần em hát sai\nCung lỡ giây chùng\nMấy ai đàn đừng sai.\nVà rồi tại ai\nTrong mỗi lần em hát sai\nCung lỡ giây chùng\nMấy ai .....\nĐàn đừng sai.', 0, 0, 0, 'Giong-Ca-Di-Vang-Nhu-Quynh.mp3'),
(53, 'Đổi Thay', 'Mai Thiên Vân', '2022-10-23 21:16:27', 'Trữ tình & bolero', 'Việt Nam', 'Bài Hát: Đổi Thay\nCa sĩ: Mai Thiên Vân\nLá xa cành\nHéo sầu cả tuổi xanh\nAnh bỏ đi rồi\nBuồn lắm anh ơi\nĐời người con gái\nMột lần mất người yêu\nDang dở cuộc đời.\nNhững ân tình\nVẫn còn nằm ở đây\nSao nỡ quên rồi\nĐể đó cho ai\nVà lời anh nói:\nTình mình khó nhạt phai\nBây giờ đổi thay.\nAnh ơi\nThôi hết rồi, hết rồi\nNào còn khi đón khi... đưa\nNhững lần\nHẹn hò\nKhi sớm khi trưa\nLời thề anh hứa hôm xưa\nThành khói mây đâu ngờ.\nNhững ân tình\nĐã một thời nở hoa\nXin trả cho người\nMàu sắc hoa tươi\nĐường trần tôi đếm\nTừng nhịp bước lẻ loi\nRiêng một mình thôi.\nNhững ân tình\nVẫn còn nằm ở đây\nSao nỡ quên rồi\nĐể đó cho ai\nVà lời anh nói:\nTình mình khó nhạt phai\nBây giờ đổi thay.\nAnh ơi\nThôi hết rồi, hết rồi\nNào còn khi đón khi... đưa\nNhững lần\nHẹn hò\nKhi sớm khi trưa\nLời thề anh hứa hôm xưa\nThành khói mây đâu ngờ.\nNhững ân tình\nĐã một thời nở hoa\nXin trả cho người\nMàu sắc hoa tươi\nĐường trần tôi đếm\nTừng nhịp bước lẻ loi\nRiêng một mình thôi.\nĐường trần tôi đếm\nTừng nhịp bước lẻ loi\nRiêng một mình thôi....\nĐường trần tôi đếm\nTừng nhịp bước lẻ loi...\nRiêng một... mình.... thôi......', 0, 0, 0, 'Doi-Thay-Mai-Thien-Van.mp3'),
(54, 'Hồi Chuông Xóm Đạo', 'Mạnh Đình', '2022-10-23 21:16:53', 'Trữ tình & bolero', 'Việt Nam', 'Bài Hát: Hồi Chuông Xóm Đạo\nCa sĩ: Mạnh Đình\nNgười hỡi\nTôi biết yêu là.. khổ...\nXin kể lại chuyện xưa\nLưu bút trong nhật ký\nChiều nay\nNghe hồi chuông xóm Đạo\nVẫn nhớ thương và buồn.\nChuyện mười trăm trôi qua\nKhi em còn đến trường\nTuổi đời đẹp như thơ\nHoa bướm mộng mơ\nNgày xưa\nTôi còn dại khờ\nYêu em chẳng dám\nHẹn hò đôi.. câu......\nNgày xưa\nEm xinh đẹp mỹ miều\nTóc thề buột cheo leo\nYêu quá là yêu\nNgày xưa....\nTôi.... học thì lười\nThương em chỉ nhớ\nNụ cười... môi... em....\nTrường em ngó\nQua gác chuông nhà thờ\nChúa Nhật em xem lễ\nTôi học bài vu vơ\nGiờ tan lễ\nHai đứa chung đường về\nEm thẹn thùng\nKhông nói\nTôi đứng lại không đi.\nRồi mười năm trôi êm\nHoa trắng cài áo tím\nKhông từ giã một lời\nTừng hồi chuông xóm đạo\nRộn ràng mừng thành lễ\nÁo tím ngày vu.. quy....\nNgười hỡi\nTôi biết yêu là.. khổ...\nXin kể lại chuyện xưa\nLưu bút trong nhật ký\nChiều nay\nNghe hồi chuông xóm Đạo\nVẫn nhớ thương và buồn.\nChuyện mười trăm trôi qua\nKhi em còn đến trường\nTuổi đời đẹp như thơ\nHoa bướm mộng mơ\nNgày xưa\nTôi còn dại khờ\nYêu em chẳng dám\nHẹn hò đôi.. câu......\nNgày xưa\nEm xinh đẹp mỹ miều\nTóc thề buột cheo leo\nYêu quá là yêu\nNgày xưa....\nTôi.... học thì lười\nThương em chỉ nhớ\nNụ cười... môi... em....\nTrường em ngó\nQua gác chuông nhà thờ\nChúa Nhật em xem lễ\nTôi học bài vu vơ\nGiờ tan lễ\nHai đứa chung đường về\nEm thẹn thùng\nKhông nói\nTôi đứng lại không đi.\nRồi mười năm trôi êm\nHoa trắng cài áo tím\nKhông từ giã một lời\nTừng hồi chuông xóm đạo\nRộn ràng mừng thành lễ\nÁo tím ngày vu.. quy....\nTừng hồi chuông xóm đạo\nRộn ràng mừng thành lễ\nÁo tím\nNgày vu.. quy....', 0, 0, 0, 'Hoi-Chuong-Xom-Dao-Manh-Dinh.mp3'),
(55, 'Phận Gái Thuyền Quyên', 'Hà Vân', '2022-10-23 21:17:16', 'Trữ tình & bolero', 'Việt Nam', 'Bài Hát: Phận Gái Thuyền Quyên\nCa sĩ: Hà Vân\nTừ nay thôi đành\nDuyên mình lỡ.... đôi\nDù vương vấn mãi\nCũng thế... mà.... thôi\nKhi xưa\nThầm nói yêu nhau\nBao nhiêu\nMộng thắm ban đầu\nThôi xin đừng\nTiếc nhớ... thương chi\nTừ nay đôi mình\nThôi đừng nhớ... mong\nMười hai bến nước\nBiết bến nào.... trong\nTuy em\nĐành phải sang ngang\nThương yêu\nNgày cũ chưa tàn\nXin anh đừng\nOán trách.... người... đi\nThôi...!\nTừ đây thôi nhé....\nAnh về sống.. âm thầm\nĐếm thời gian\nXóa mờ dĩ vãng\nMến yêu\nAnh...\nXin hãy quên đi ...\nCho kẻ vu quy\nCùng người trăm năm\nThề nguyền gắn bó\nThủy chung muôn đời\nTừ nay thôi đành\nThương gọi cố nhân\nNgười đây kẻ đấy\nCách mấy đò ngang\nĐôi ta nào phải thiên duyên\nGieo chi lời trách ưu phiền\nXin thương dùm\nPhận gái thuyền quyên.\nThôi...!\nTừ đây thôi nhé....\nAnh về sống.. âm thầm\nĐếm thời gian\nXóa mờ dĩ vãng\nMến yêu\nAnh...\nXin hãy quên đi ...\nCho kẻ vu quy\nCùng người trăm năm\nThề nguyền gắn bó\nThủy chung muôn đời\nTừ nay thôi đành\nThương gọi cố nhân\nNgười đây kẻ đấy\nCách mấy đò ngang\nĐôi ta nào phải thiên duyên\nGieo chi lời trách ưu phiền\nXin thương dùm\nPhận gái thuyền quyên.\nĐôi ta nào phải thiên duyên\nGieo chi lời trách ưu phiền\nXin thương dùm\nPhận gái thuyền quyên.\nĐôi ta nào phải thiên duyên\nGieo chi lời trách ưu phiền\nXin thương dùm\nPhận gái thuyền.. quyên...', 0, 0, 0, 'Phan-Gai-Thuyen-Quyen-Ha-Van.mp3'),
(56, 'Nhớ Người Yêu', 'Trường Vũ', '2022-10-23 21:17:42', 'Trữ tình & bolero', 'Việt Nam', 'Bài hát: Nhớ Người Yêu\nCa sĩ: Trường Vũ\nNhiều.... đêm ....\nThức trọn ...\nNhớ thương em\nNhớ quá ....\nLàm.... sao ...\nBiết ngõ.. tìm....\nTay... trắng...\nAnh nào\nMơ.... với mộng\nNên tình hai.. đứa...\nVẫn... chưa yên...\nThức trọn đêm nay\nĐể nhớ...\nThương em...\nAnh nghe tình yêu\nNhắc nhở êm đềm\nNhớ từng nụ cười\nÁnh mắt\nNhớ lời ngọt ngào\nÂu yếm\nTóc em thơm\nGiấc ngủ dịu hiền.\nBiết giờ này em\nCó nhớ....\nAnh không ?\nCó nghe tình yêu\nThức dậy trong lòng\nĐếm từng\nMàu thời gian đến\nBóng hình\nNgười mình yêu mến\nÔi nhớ gì\nHơn nhớ người yêu !\nEm ơi\nLòng anh thì rất chân thành\nƯớc nguyện\nTrọn đời yêu em\nChớ đừng giận hờn\nAnh nhé\nEm ơi\nĐừng bao giờ nói chia lìa\nSẽ làm tội nghiệp anh lắm\nĐã thương nhau\nChớ phụ tình nhau.\nThức trọn đêm nay\nĐể nhớ....\nThương em\nSương rơi lạnh câm\nCảnh vật im lìm\nƯớc gì\nMình đừng ngăn cách\nƯớc gì\nNhà mình chung vách\nHai đứa mình\nThức trắng đêm... nay...!!\nBiết giờ này em\nCó nhớ....\nAnh không ?\nCó nghe tình yêu\nThức dậy trong lòng\nĐếm từng\nMàu thời gian đến\nBóng hình\nNgười mình yêu mến\nÔi nhớ gì\nHơn nhớ người yêu !\nEm ơi\nLòng anh thì rất chân thành\nƯớc nguyện\nTrọn đời yêu em\nChớ đừng giận hờn\nAnh nhé\nEm ơi\nĐừng bao giờ nói chia lìa\nSẽ làm tội nghiệp anh lắm\nĐã thương nhau\nChớ phụ tình nhau.\nThức trọn đêm nay\nĐể nhớ....\nThương em\nSương rơi lạnh câm\nCảnh vật im lìm\nƯớc gì\nMình đừng ngăn cách\nƯớc gì\nNhà mình chung vách\nHai đứa mình\nThức trắng.. đêm nay...!!\nƯớc gì\nMình đừng ngăn cách\nƯớc gì\nNhà mình chung vách\nHai đứa mình\nThức trắng đêm nay...!!\nƯớc gì\nMình đừng ngăn cách\nƯớc gì\nNhà mình chung vách\nHai đứa mình\nThức trắng đêm nay...!!', 0, 0, 0, 'Nho-Nguoi-Yeu-Truong-Vu.mp3'),
(57, 'Nỗi Buồn Gác Trọ', 'Quang Linh', '2022-10-23 21:18:09', 'Trữ tình & bolero', 'Việt Nam', 'Bài hát: Nỗi Buồn Gác Trọ\nCa sĩ: Quang Linh\nGác lạnh về khuya\nCơn gió... lùa...\nTrăng gầy nghiêng bóng\nCài song thưa\nNhớ ai... mà ánh đèn\nHiu hắt\nLá vàng nhẹ nhẹ đưa\nTưởng như bước lê\nHè phố....\nCó người con gái\nBuông tóc thề\nThu về e ấp\nChuyện vu quy\nKết lên tà áo\nMàu hoa cưới,\nGác trọ buồn đơn côi\nPhố nhỏ vắng thêm\nMột người\nBâng khuâng\nGác vắng khêu tim đèn đêm\nNhớ nhung đi vào.. quên\nSông sâu\nCố nhân ơi đi về đâu\nGửi hồn chìm vào đôi mắt\nÁi ân chưa.. tròn\nĐể ngàn đời nhớ.. nhau\nPhố nhỏ\nĐường khuya trơn lối về\nDâng sầu nhân thế\nĐộng trên mi...\nCó ai ngồi đếm\nMùa nhung nhớ\nNỗi niềm đầy lại vơi\nMỗi mùa tiễn thêm\nMột người\nBâng khuâng\nGác vắng khêu tim đèn đêm\nNhớ nhung đi vào.. quên\nSông sâu\nCố nhân ơi đi về đâu\nGửi hồn chìm vào đôi mắt\nÁi ân chưa tròn\nĐể ngàn đời nhớ nhau\nPhố nhỏ\nĐường khuya trơn lối về\nDâng sầu nhân thế\nĐộng trên mi\nCó ai ngồi đếm\nMùa nhung nhớ\nNỗi niềm đầy lại vơi\nMỗi mùa tiễn thêm\nMột người\nCó ai ngồi đếm\nMùa nhung nhớ\nNỗi niềm đầy lại vơi\nMỗi mùa....\nTiễn thêm một người\nCó ai ngồi đếm\nMùa nhung nhớ\nNỗi niềm đầy lại vơi\nMỗi mùa....\nTiễn thêm một người', 0, 0, 0, 'Noi-Buon-Gac-Tro-Quang-Linh.mp3'),
(58, 'Nhật Ký Đời Tôi', 'Trường Vũ', '2022-10-23 21:19:12', 'Trữ tình & bolero', 'Việt Nam', 'Bài hát: Nhật Ký Đời Tôi\nCa sĩ: Trường Vũ\nNgược thời gian\nTrở về quá khứ\nPhút giây chạnh lòng\nBao nhiêu kỷ niệm\nBao nhiêu ân tình\nChỉ còn lại con số không.\nAi thương ai rồi\nVà ai quên nhau rồi\nTrong suốt cuộc đời\nTương lai.. trả lời.. thôi...\nMột mùa xuân\nNăm nào hai đứa\nNgắm hoa... đào... rơi ...\nLo cho số phận\nLo cho duyên mình\nSẽ thành một kiếp hoa\nSớm nở tối tàn\nĐời ai không một lần\nQuen biết rồi thương\nYêu nhau rồi lại xa.\nThôi... thế là thôi\nLà thế đó\nDĩ vãng là thơ\nĐem thơ về ghép nhạc\nThành khúc tình ca.\nThôi thế là thôi\nLà thế rồi\nHiện tại ước mơ nhìêu\nCuộc đời rồi đây\nBiết bao giờ\nMới được... yêu....\nNgày biệt ly\nChúng mình chưa nói\nHết câu... tạ.. từ...\nNăm năm cách biệt\nNăm năm mong chờ\nHéo mòn tình nghĩa xưa\nNhắc đến thấy buồn\nTình kia ngăn đôi đường\nNhật ký đời tôi\nGhi thêm... một lần....\nThương\nThôi... thế là thôi\nLà thế đó\nDĩ vãng là thơ\nĐem thơ về ghép nhạc\nThành khúc tình ca.\nThôi thế là thôi\nLà thế rồi\nHiện tại ước mơ nhìêu\nCuộc đời rồi đây\nBiết bao giờ\nMới được... yêu.\nNgày biệt ly\nChúng mình chưa nói\nHết câu tạ... từ\nNăm năm cách biệt\nNăm năm mong chờ\nHéo mòn tình nghĩa xưa\nNhắc đến thấy buồn\nTình kia ngăn đôi đường\nNhật ký đời tôi\nGhi thêm một lần....\nThương\nNhắc đến thấy buồn\nTình kia ngăn đôi đường\nNhật ký đời tôi\nGhi thêm một lần....\nThương', 0, 0, 0, 'Nhat-Ky-Doi-Toi-Truong-Vu.mp3');

--
-- Chỉ mục cho các bảng đã đổ
--

--
-- Chỉ mục cho bảng `account`
--
ALTER TABLE `account`
  ADD PRIMARY KEY (`id`);

--
-- Chỉ mục cho bảng `categories`
--
ALTER TABLE `categories`
  ADD PRIMARY KEY (`id`);

--
-- Chỉ mục cho bảng `categorys`
--
ALTER TABLE `categorys`
  ADD PRIMARY KEY (`id`);

--
-- Chỉ mục cho bảng `reset_token`
--
ALTER TABLE `reset_token`
  ADD PRIMARY KEY (`email`);

--
-- Chỉ mục cho bảng `songs`
--
ALTER TABLE `songs`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT cho các bảng đã đổ
--

--
-- AUTO_INCREMENT cho bảng `account`
--
ALTER TABLE `account`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=14;

--
-- AUTO_INCREMENT cho bảng `categories`
--
ALTER TABLE `categories`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=40;

--
-- AUTO_INCREMENT cho bảng `categorys`
--
ALTER TABLE `categorys`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=33;

--
-- AUTO_INCREMENT cho bảng `songs`
--
ALTER TABLE `songs`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=62;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
